# from textwrap import wrap
#
#
# def ss(string):
#     return [string[i:i + 4] for i in range(0, len(string), 4)]
#
#
# def com(x, y):
#     r = ''
#     for i in range(len(x)):
#         if x[i] == y[i]:
#             r += x[i]
#         else:
#             r += '#'
#     return r
#
#
# def rm_noise(s):
#     places = [0, 2, 5, 6, 8, 9, 11, 15]
#     a = wrap(s, 16)
#     r = ''
#     for w in a:
#         for p in places:
#             r += w[p]
#     return r
#
#
# def shuffle(s, table):
#     a = wrap(s, 8)
#     r = ''
#     for w in a:
#         for i in table:
#             r += w[i - 1]
#     return r
#
#
# def decode(s, table):
#     a = wrap(s, 2)
#     r = ''
#     for w in a:
#         if w in table:
#             r += table[w]
#         else:
#             r += '?'
#     return r
#
#
# def calc_dict(sample, encoding, table):
#     t = rm_noise(encoding)
#     tnew = wrap(shuffle(t, table), 2)
#     s = wrap(sample, 1)
#     d = {}
#     for i in range(len(s)):
#         d[tnew[i]] = s[i]
#     return d
#
#
# a = 'AJAOFBKCOCHMLKAOFDGELMDIIHHEJPKKKKICNAFHHMEAFPBHNPABKFMGACHGNKCAHJFHNKCEEHFIBAIMMKEEBEAOJJFOGFFADPDIBKAPIAHILAKKDFEIIMACEABEAKCMKHIKGOACAJGNBFCAKECIBNDOAPBADEBNAMAPINKJFINAOCGHAFJLAIADMABECBHFNCAGKDEPHOHHFHACAOAJBNACIAOAADHOMGCNNOKHPIGOLCEDODIGCHECEJMFLMGIHOFECANMAOIAHDMAFOGCIKCPIHOIBMPKCLKHJFHCAHHMGIMAMMEKHCMPNCMHPBDOKLIMJFDJBPHGIGNEACAGEKMHNEDIOMBOMNCFBIHFGFIEPJMFHOFEDKFFAGEIJCBNACAGCFNCGAFNOBGFNHOKMAHJIFCJAPNKDAHEMFHCAFFMDIPAIFEMMKNDCOGILDGMDKHABNADJACACFBEDDPNAOACBAKNNNEECDHDKKNIDACIPJPDOGIOJANGAADJFHPFOOILLPAFIAHCKHJOMNELAFAFKJAGADHCKCCIBOMMECBIDLKMKCINENKPDIAOMHEDFGAJGADKAHBAGADNNOOFMFAIAJFMPPDNELBIEOHJAFBIIMBACEKPIAODINFAOBBKABAGLMNOJAJEPEDAFBGNGMHAOHKCHFAOMEEEFDOBJICPBGIAAFACOEFOFMABHMBHMNEEIOEEPBONKFBDKDIMODFDCNFPAFBMFAAEPANFJADAOOAAOAILFKMNGEKCEFJFFPNOODKAJIJPAFBAKJKCPADBIPAACLPKEAOIOFAKEAMNIBBMOAIMAMAKPAKCHBHDADAAFOCDCHNILDNMOJNCKMFECGLEGIFMEPJHAHKPACCFGDMADIHPPMHGAHGEHPEAOLIABCMDACFHEJLAMFEBODKPNIPPKCFONEAEIHOBJIFFKJBAANAIJOAGFACIILFHFGMBCHOHNIPFCKFBNNAOFOMEGEMNBOCFFONEMDFNJMFPMIGAAHADPINMHAPEOBBCKDIAKINLJGHEHNLAOBEHPAANIAJAOEBKMACGIHCLEKNFPGDMFDGPLAAJAJCAGGBNKEIIFNFIFMOOCKNHACAPECNPCAAKBBAKFNGCFMCBBKOCEPDEHGFFGAMIACNAALEAMOCBOKNCGANILJIFABANAHMGGEBFFEBFAMJFGCKJICCKPDHOMCCBHMKFOIPEMJNNKPIADDFMAADDJICADEHDLNNCMOCAEFDFAGJHFNEBIBHADAAOHDFGBAKJKIBAJHNCOHILMOOMPIJNJBADOONPNAMNFEAAJDAHFPGKFLOHHIODGFJCDGHPCAMNACHAAFENMEEJGFMJHCEGOAMCOEILNNABEABOHPAMOLIONFNDHABGLHOHBBEMNABFPGPAHCKGACADKENIHAJJDEIDFKGPDMCOEHICOIGMNGOENMEDABBCLMANFJGLLAHBIHFALKAOAEAFLNNPEHFAEOMBECJHCBOHANHGCCNAMMEDJHDFAHDFIKEAEPOGKNAAIJBAKLGOADAFCFACCAFMLPAMNFAKDFNEHACABMLHAKJHBMDOMHGCLHPFAOAFJONNCADIMEOKFMGFAMDEBHACKOEEAFAFDOAAIAJIKOPOHGFAOOLCEDBNJCDMCLHLAFAGIADGOBKONCABBDOBOIHHOFOEFOMCNAMPACEJOODADNDCIACEIHMAINFKKOCDJJDCIHPPGDDOOMIBHAMEACIALFFANKAILDKLAICHBENFAAJMIKDAMHLCKCEFAKAAJONCHAPIEMADMOEPEFOEHIMGOIPCDBPLJNDMAHEAKDKNNNGOHOPAAFMIHHNACOKODMOPJIMEJHPAMNEOCKNFCOLCNBJMMDECKKFLAABIJCFADCHDINNKMOGAKNCFAJJNJNMAIEFAICFONOOHCADIIPMAHDAKACJIGKFFJMFIGANADBDFGANOPADAMIPDAOJBLHCCMKAFIKHFMDCCLADAIPPAINLONIOIJABCANFAIGNNKBIPJOKEDIENPHDDNBOMMACMIHKABMHKOHOMMHNPCABHNPFMKBIIEAOBCOPACCKMMEEEKDFMCGNEIEBMDEPJOHDJBPNFGKFEAIAPANMKHEBAEDPCKJIGGDFPJGHHBOCAKCIAFAIKDHNJDDPLNNABDHOPOOHFEAFNPNCEGNKFIIGAHCGOALJEPAEDABDJEKPNDCDKLAODHOFAHFLCHOHIGHAMAAHHDPGNANABMHKKCINFAAMMFKGCIMHKAFBCFPPNADALDMKPOIHEJADNHFHFGCMDOCKHOIPOKDILNAAEEAFJDIMIKBIDGHHBNFEHLHCOBJNGHOKCJIJIFPEAAAAKAINAGAAEJBDFNHOGFACMIHEJIOEKDMHBOMAPIJJELKFKAPJDOFIEIEJGDPJKKDKBMAFLAAIABIINEPJBNFCEAHPMDJMADAHEPMACIJPEFACKAOJICFIEIEBGKBMKCLHHKAFKIGBAJDPKAPABOFCBAHCMGDANMPEKFDMPECOHILLIKGIGMNKCDINOEGHDFJGGBAAHAJNALHBNKMIKMNMPHENOHJBCKKIEMDFOJGEHDMAAKBIPLAKBDIKJBOBDKOKHMAFMAGNADCPNDPPHKNKANILABFIFNNABFAAAJAPJMKHEHOFOHINOAOPHEIFNCCHLPKFMIGEIKBFKAMAKKFABIAKMMHDOMEEINDOCGOOPIFLFNIOHEKAMIAGCDADONPOBNMNDPAKCIFFDNHAMPOKMAKJNOCBAKAILHCMPJEFHNKAANPAAEFNDJOGGCCJAHEFBEKDAIDBIJICKAFAGFKDHIHCIBMBODDEFBOMDECNODBKMHGFOFFNNAGEGDIINOHEEEAIPAHCAANCAONIICFAFKAKGEJCCCPHEBDHBOHMDNGAONFAOAHAEKALHLANCFNMHPKOCPIBKONFDMKCKCAFNIAHAMPBKNKAHPOFKJMPNFKJAOHNGKANFFANANKCHKHILJAONGNPALAHFDJPLMMAMEJJEJPJMEKBGAOFHAGKIBBHACOKMAMOPJIKENFPAMPECCKNGCOKCHMDMIIEPOKCKAHMIEDHAFNAIONMOFEAAIENHNAOEGOEPIJKNEBPOHCFMNAFMAAAAFMNAOONIHNKEACAAPEENABAMHOKEOINOECFNKPIBFFFDHMOGHMACAIABFCCNFKPKBMMHOONMFKDAIPOILPPOAHANLKKCHIFIEINHOFNDHOCKEHFNCPEMNLAPABOCJILNCHPAAKAAIMHOCFBEHMJMFJANIEAFIAFBEJKOMAECIDOPNNCHDPBBAEACCOMGHEBOHIMCKLIIDDFFJGHHOABAFBMBCAOCHIFJGHHDHAHJOAONINCALMBKNGAHJCOAANPHBFBFDJPLNMADEJEEOJCMEMBFGOOGHINIKKHDNMOICACPIHFANKCKOJOOHHNHCAMHKJBMAMABCEMIOCDJPMIONMAELFKIJIPGMPIADDPKKHAEEJDFLFFMMBECCODBAHDIHIBAMLCCEMADGAMEGEMFFOMANHKJKIGFOPDCNFADBOOKAIINHDBAAMAIGFFCCGNAGKNMKEILBCAABAEHPJKENAAJADOJOILHNBIEENJAPAKEAIJJGFDACFHFNHOAENEHNNEMDCPANMACEJFEFPBMMDEPKOMEACBIJBAAMNEJNFMEHEBGICPHOKICJACHAHAJOJFADJHBBMAEIJEEPMFKNGALKFOHAIBGFMFANMOJJADIIPIAFECKKHCFCOMBECHIALPMHOFGJFANAAMGKJGNMOELNAKFIKAJDJFKKFICPCOONIPKFEHOFDMJBDAMKANHOMACNHAGBFNDHANAGIAHAFJEAMCPMKNCHBPFOENCIAFPEGNAAKPMDIPLCNIBEEBAFPFMODIGMADJAHKALMEACKKANMAHAJCECKFNFDANMOKBHIFIMNPDNKGOCHONAEHFDIBAFDICJMOBANMCINIADEPGAMDAAPFEOBBNMOCCJKAONAFIDDFFDIPAAOAMBACNDDFEKDIIDFKPDIAGEBLDAIAODEFECGIJFANKKMKMNKABMAKICDNFKHKKAKMCECLIFNJMMAEBEHOJCIIHLCCKFENFEFFDACGGGHPAONIDKBAFHACPFKCCNAAGKHMPOEKFBMAEONOFADOFANKHGKPADGHCNKEHOJNIFELONPAAOAFGAAIAKBCAMEEKJOFACNBNCFLMHNGDPAJPGAAAIGMAAIAMGCOLJOHDCKKAHFHOPAKKICDAGKBKOHILCFHDAHCGPGCAKGIGPCFDCGEHPEIMABANLKNBGAAIDLOFAFANMNOEKOGOJPNKMCEBLOACGAANFDGFKNIDHNFAJGMOABHAKMINGCFKPNGHONCDNNAOFAAABANJAAPECIHKBCFOAAICMNBNMDHFHNMPACAAMPCAKEIMPHHPEFJFHHFMMDENJCMHHEAHJIPDAOJDHAMFIEMJNNJKHOFANAMOICPAIKAKFBGGAMAGAJCCHADNHDFPCKMMPEHIAAEDOBIEEAAEEAPJDCIMNEAHBDMJGEHHFCCFOJIPPCDMAPEHNAHNAKJEKFICIEJNNPCKKDCELAMCACCADEGNOMIGOFAJAJCGOOFAHFHKEMMPICKEOCFKMNEPKCMKNCBHFNHOHBFOPFAAEJEGLFBMKEIAAAAAAJAJFEJAABAGFNMFHEOAHPEDFFGPHMAHEACCGDEMFEMBMHKFKIJFCFNCNMAOPOMBAEDNNKPAAMAHGMFPIAEEIKIOMKCOMACNGHJANPCFEOBGOKAFGACIBIHNOENONONBJAKKNNPAKLIMFNOGANOOMFKAEFBPNDHPAHEPFKPAKIIGCCFBIACHEPDOKPICMHMBNCPFJMIOHJFNFFABAAAGEJPNMLECLCKJHIMHDCBDFPGKLAEMAJPJFNHNFIGJCAMCHEIAAKMCKCIILKNIFADKKKOHEMOEHHDPEDMFKJFMAKANFKCHHHNILFFHOGNFKKDKIPFIMFCKOFIIFBMHGEANBBNFFJNGEDKEJIIPHFCAKMIKIDHFAFBDKBHAMEEMNCMFHEBHJBPDOCIAOAAHJAPJAPJEAFAKMHKNOINFBGDNHGHLLCMDOCJHONJOCPKCCNKMACDAHPHACAHHAMFNEADEAPDMNHOEKABPANBAHIKNFDMNCOALEAMNLKPMHHPABHCNEDNGLALGJCAPAJNHAOPACMGAAGAKHDNFJACHOIHAMEEMPDNJCAAHFKGKOIIKFDFMCNDPECOMMKCKIAKHKIOAKLBKAIJCGCMOMEKHCHPFHHHIDAANOJDABHGOFBGJGNAHMAGOIMIFHJFNONCEAHJAFEFNIDEAHOFJJMMIOJLAAMAPDCNEHAHKHCMDOGIAMENIJGBOAANABIPGBADBAPHAONDNEIBMANABAJDAEAKAMICAKNDNEPOAMGPMAEJOKMKGJILEFPCAFFGAPMADNAPCNGCFADAKGODLCPNIOAOMKJKOLNMBIEFAKCEKIEHNGAKDOICAOMGNKBIMCAOEHIMJKOBDMIEABKNOCOICDIDMMAEJAKCKAHBIBNHAFPALGNOMFICAHMHHOLIFMFADEABGAJPMEHBEMCNMNAPHDPBOCBHFBAICAECAGIANAHJHKKHMIFHIPDPKAHJOFAAIAADAHHCNNGADEACIHHCJDMCHHIFIHNMOPEIADLLDOBIMJAAMIADJBNJONOAKDAFPCGCJDJOMHKHHOOFJAGNOAKDNDIPOEMAMNJIEEPFFCAKGJFOKANMMBONAIDEHFMFBCGAEMGJMOOIPGHEJEJDFKLBIADJMHAHJAHHACFJNOGIBPCMFHEHHGHNDEEJHBCFFABMHNFMAILEJOLDKADMDDDCANDAOMHOMHNIFFDMCINEMPMNOCODEPPEMIKEBIKFDAGMIOFEAAHJGNNKAOIGAEFGNKLINDHAJEAHFFEOICHHCBNODHIOAKJLDELJEMOHJAFBIFAPAFKACFFNNFAAMKBCHOCIAJDADAJEPONKAKNICLMCOKKKEBNKKONNEOKDKIHMIADGOMPCMDKFPGNBICFFFMACHGAFFIABACIPKNJADGOOAJIFNMGHAAKAEOENOAAABILAFNEADLHKFCIHHACHMANAHMHNNHAFFNCNDMEEAIFOMHIOGGCKCDPPLENAJNJIAEKMFCAKAHFMDACHMLFLAMBEHGCMFNCBHNGHOHCFBMFADAJPGOJBAAFAJKNMMFEHACFFHFLNLBMHDAHOCGBFACIHIAMKBIIBEOOEOANAJKOKPKICNPDCKHFFNIMCDMKOEECAFOGNEOAIEEECAHAKMFGGHEMOKFIACANNHAEAGJICFAHPEBAANOPILPDNEIGJHDPDOOMEKCAHHMHIACPCFDBPDIKMHJEBIKKLAOHINFAADEAKJMEBMFEGBBIIGIEMHMPAKFNAMBAOKANOANPPNKFCCMNAAIAGAMHHOFFMNKKKEPIOKMPODMNCFJAEBFBDAKBEHNDANDFKMJIJAMNOAMGCFBAMHACNAKOAACEHMMMMJNEPEOEGFALJEPFDAMHEAOAFFANAMKOCAGHBILDBFOGNAIOKFJIOOPMAAFNGIHMDGBHHCGCKENCGIFOBPAMMIOAEAHJFBFACEMKAAACNFOMNKFKDJIHPIPGDKMDCEMAMJIENADPBKOLILJOMFJEINGNKAOKIMKAAOEADJBFCIAAAMFHFDFMMFEGGHOAILABNBNACNPEAOMEEBMFFPPNNGDCADFFMLEAANEAJJLGAINOAAGCKOEIFHPJPIACAMIAMFOCCJPDIOKPIBPDAMNJEPONIBDPPEGOMAACHIHJPNAHAGBFCMIHFNOEGKNLAKLDOAJIJDJHJANIAJHFOECICAHMHPAMADEEKIHIABLFAHHBFMHOFGIADNBEBKEGJLCNFKAGIAMEMANGOKHNNHAOJAMJJANFOBKNOKAOFALHIANAAPKOMLPEDNJHJDONICAAABEAJJKHFMFCGMOIDDIDJHKLPKAMADLKNBHAJIPEMCKLILHINKJADEKLMAKMIHIAACGANABICFFPGBGMAMAJNCJACNOKINLPANIAKCOPBOABJCOMKOAKICBEFNMCEEEBODJICNEIJAEEJIDECOAHPBCFGAMCCPCNKIHIPAJMHHKDIKNDMBNEEPNAFBAIJDEAIMIEGJKHEKHBFEKADHAHLANABAAMJMLKKEDIHIOBHDFMNGIDNFCOBPIMDMDCHEDKDFADBIBEFAACALLNKDLIDGILHJKHKKEIDCAPGENGDNNJAIGMEMJJACAJNAMHCJHAMCICBAEGAKNHAEGFDDFPIGEKIHDLPFDEAMIAMBFMCKKKIKNKMCPEGKKLKDANAKDMJCGALEFNHAAEAGHJDCOHMAPGHNAEAINEABAAEJHFKNCJHBDFAFAJEGDBBNHGHKHMCAIHICLAKKAKJEAFCJMKAGNPCFMOCAAAMMHEKAFHBCMCCLBOHIGFANIGHFKMKFLADFMPKACFOFAEANCKMJJEKIDDCAKDIIFOFCCGCNEKCMFPGNCNKGICBABOOKKDIBNAABGAOJCMGNKIIEOAFEHGBLNNFIDLHCGKADOAIIOAPODFPINOADBAKNBHBEKEILMHHDNFNHMPGOFMAGAKAGAADINKANMHEHHAKCIKMJMFIKKCIDJCOPNIAKBGAOFNMHLDABKACHJEJCNLADPFNGHAPAGGEHKEIAJMAIFADCBAPHMKCHEKKJJIGIHIPAAAJGGHCAMKFFBGIFHPFEMAOPINHAPABOHBFOOKOFANAIGGBAHEFJLKDPIPAIFPFKMMCFAFHPGFLNBIAFEHBEJOOAAIEICCAAHIHGFMDLIPACHCKKFNAKIFHAIFMNKFBKDHPEONMAICIAADAOAEAHEFMGFEONFMFHFKNOOMFBAGBCIONANKAMMCMCJCGHMIJAKOIAEHFEHGAHNNLCNIOOBACOIHOAJPPKOHOANHKMCINHKLNMEFJJBHNOAABFNBPADIHHCCIGEEMHCFMMNFOIEMMCIEACEBBOMACPFAMLHEPADHGCMJCFHOHBGFPNDDKFAJAGCNKBHIBAHBFHHNFJDOFCIAPNHPCKEFJBMNKMACKAJHGAMICCHNOFGINAALFFAHJFMKACIAKCFEEKFNALMOKKOIIODMANKOIEFNMBPEDOOJCDAJJDPIEEABBEOILNBDNAAADHEPNANKBMFLALEMNMJAAEHHFAAGAGHEKANIJBNFCOKOINCCNJDABHGAGDKPILIAMJCEKAHNHKFHNODAANAJDJJEAAFHABJOKIOIFIEIENADALOICAHHNENGCHHJHOMKMPOCBIHNOOAJJLENIFIECOOOMKMOCIHAKPHIDAEMNHKGIGPMAGKJJCOAHKMCCLKKOPGICIPHJFABACOECHHHPJBIMHCDKNAKOEINDIEKPKHCFNLONMOAKIFEGEAHAAHEFCIGFBOEAKJELDCAIIIEKADJLKNLANMKMJPCIKBOGDAFJDBNAOAAAALAJNKCILLOPLAFMNABFADGHDBNNECACAJHLPLJDLHDOHHOHDGEKNNDAFADNMOAPPPAHNAHAFANKMEICGPBDOHHFNGAMNHEEAGIECEIBNNDKFAKFHKFEAMCELOKFCFMJIJHPHAEAGECMCNECKHCFOMCCMFIHIGFHEBEPFIDELIOOEANGINKAAEIBOPDMKACMPHPCANDADDABCKNCJOIHKAEJNFMEPIBMEDEAOFCGDHAAMAJPAPBDNKHICPNKMFIPOINLHAOAOOICAAHOEGKMNOLIIFDAJIACHOPEOKHINJHKCNIEFIKPOAMAILIANIACEANNOKJIIMDJAHPFDJDOCOGIOAKAIHAJCLJEDCNHDIHHOIFOHBNHOMIEAGDNLOACPCFFNNDAKBDFICNFPPELMOAIOFAFLAGPAOEOANEAPACMGJCBHHMJAKIIKHHFFHGHHKFKCNPANJAAABAMJADCEHOFDHNNJIAIAOOCOOMICAPNCBGPCMFDEMBBAPIMABBJMDLBM'
# b = 'NDAHAFNAJOLGCBMAHIFJEKIOIECIKJBK'
# c = 'NGAELFNBJOJGHCAAHFFENKICIECIMFIK'
# d = 'MIBNLCMCBBADNNBMMFBFJMMNBBBBNPHM'
#
# tab = [7, 3, 2, 1, 5, 8, 6, 4]
#
#
# def ex(t):
#     d1 = calc_dict('танк', b[0:16], t)
#     d2 = calc_dict('овой', b[16:32], t)
#     d3 = calc_dict('1___', d[0:16], t)
#     d4 = calc_dict('____', d[16:32], t)
#
#     dic = d1 | d2 | d3 | d3 | {'AA': ' ', 'EB': '«', 'GB': '»', 'FP': 'Т', 'HN': 'Г', 'EG': '--', 'AJ': '0', 'PB': 'М',
#                                'LJ': 'Ч', 'KO': 'О', 'IF': 'ё', 'AF': 'з', 'CP': 'ц', 'IO': 'и', 'NO': 'д', 'ED': 'щ',
#                                'FH': 'в', 'EI': 'й', 'IK': 'о', 'HC': 'р', 'OO': 'у', 'GF': 'т', 'EM': 'e', 'HD': 'м',
#                                'BE': 'я', 'PD': 'л', 'JA': 'н', 'ON': 'к', 'AN': 'а', 'JE': ',', 'LA': 'П', 'DD': 'г',
#                                'CM': 'c', 'KC': 'x', 'PJ': 'ю', 'CK': 'ч', 'KJ': 'К', 'HH': 'п', 'MF': 'ы', 'KK': 'б',
#                                'NF': 'ь', 'IC': 'Г', 'CC': 'ф', 'NB': 'ж', 'GN': '.', 'KJ': 'К', 'HF': 'Н', 'EO': 'В',
#                                'OE': 'ш', 'DL': '-', 'FN': 'З', 'LH': 'И', 'HI': 'э', 'MB': 'С', 'FC': 'Ш', 'PG': 'А',
#                                'OP': '2', 'GA': '3', 'KB': '4', 'PH': '5', 'BF': '6', 'GH': '7', 'AL': '8', 'FO': '9',
#                                'CF': '(', 'HM': ')'}
#     print(f"Dict: {dic}\n\n")
#     print(decode(shuffle(rm_noise(a), t), dic))
#
#
# ex(tab)

# from itertools import permutations
# from textwrap import wrap
#
#
# def ss(string):
#     return [string[i:i + 4] for i in range(0, len(string), 4)]
#
#
# def com(x, y):
#     r = ''
#     for i in range(len(x)):
#         if x[i] == y[i]:
#             r += x[i]
#         else:
#             r += '#'
#     return r
#
#
# def rm_noise(s):
#     places = [3, 4, 6, 10, 11, 13, 14, 15]
#     a = wrap(s, 16)
#     r = ''
#     for w in a:
#         for p in places:
#             r += w[p]
#     return r
#
#
# def shuffle(s, table):
#     a = wrap(s, 8)
#     r = ''
#     for w in a:
#         for i in table:
#             r += w[i - 1]
#     return r
#
#
# def decode(s, table):
#     a = wrap(s, 2)
#     r = ''
#     for w in a:
#         if w in table:
#             r += table[w]
#         else:
#             r += '?'
#     return r
#
#
# def calc_dict(sample, encoding, table):
#     t = rm_noise(encoding)
#     tnew = wrap(shuffle(t, table), 2)
#     s = wrap(sample, 1)
#     d = {}
#     for i in range(len(s)):
#         d[tnew[i]] = s[i]
#     return d
#
#
# a = 'AJNOLJKODNNIKHBKMHPAIEFKJBNGCMEPFEKNEMADIHFJPAHLMCJAOEFIBHAGEFFCAADCHAFNBMMGOBFEDHLIAPDMFCKDCIBHAKMOCJMNFDEEACCGHNDBGHAOEAEAINGBNAIACAHKDGADIDIFMKDNDEADJBFJPDEJOFGOBEADEMOAHNJEKLNCGIFKBHMGIAMEAHHOEAENNOOJOCEBKEAALINHIPAOFBLAKMCIMICFBCKHGHDHKILAIIHDCJAHHGADMAGJLCNAKPAAADEBAANIHJEFBFKBGLKOBHBPEMAOBFJAIDJIOCHABIDFOHNPGDGFCBNAFCAACENAJAJFOHHOCIMOMBNCIIIINIAICAHCBJKFHKPDFDOIMNMDFLOCPDAEDKNHFPKACFHIAKNGKEPGHCOOHEFIIOGAOADCOINMKIMOEPGDMGAAFCOMCCAOEHINOIIIEIHDPJKFPBHNKNOAFCOEGKAOBNINOONCDIFNAFMGANBEBBOACMBEFNAMBAFJHBDJFFABNCDAMMKDIFEFFEKAIEHIANMMAHIEDJAAJBMAJDKBNHKAMAHNCOADAPNOMEANEEADOKFJPDEFKDNAEIODJDAEHLEBNKGGBOKMECFICOFNKNBJGKAMIJEAENECMNLPMCAFONDAMFHPNMJDIADKGMDPIHPINMAICAHMICKFCJGAJGCAHACAGCADJHBBHMECBFMANACEAHGDEKKAFBDCNBNPHLMCNOPMAAFABNBGAJFMFKEILMADDGOJPNEJBLBJAPADFMEAHHPEFHNPCGKKGCDIIBKODLKFDHFKAHHMIHPFODBAOODENHAJJEMHDMKFJPMFODHEAGAHDEAGKHKFLGFINPPDCJBIKIAAANOAAHNOOIBHKICNKBCHALEHKCEAGIADILNJHHDMOJBGDEADKBNAHAHFHENIIFFAEDKGAMLEAEBGJJAMMAFAEPNNKKFAHIMNFCACAFODMPNPPCNDHBDADAMCDGJEGJAOEDMAIEGMOMACPIMKDCMCIHOAMJKACCHOECAFIPOLOGOOGIHFPMOHGADCHDONBFAFIBFAGEGCINHFJEKAMDHIAOKHHACODHAAJIOAJFJPOFBIPIFCPJKGHDACHEAAFHBHGAADFPNJOJFJGIOKPJAIIELCCIGCPHMAOKKEAGFEOCMACNAMENFAELBKFLGAGGLHPENDFFGKDEGILHACKDOAHGGKPGOCFCEMJKMBEKCOKGMACIHNFBAHAHEPAFCPBAMMEJDECHDFOBFADIHNLDNHOCHEEPGOEBDFGOOPGBKEAAGIAAOPDNOICFAHDHJEJHCCDNMHIAMHOHMJHIONBFAIAHGKGMDMFPCAJCBFABFLEHFIMBKAHCKKANJMOEPAOIDFFFNPAOBJHGONEHAMNKFACDCPMOCNAEOKDIONINOBFAMNOGNCILBAHLIICODABHFFDGAGNBLDHJFKJFKMPGKIECEMENCJGBONLCAIAGDHFMDAHMHEBHAFJGPCACOFPJOODPHINLMFMPAGLEFOKPFMOEDLHDOCBFKAOCMIAHDINKMGFOMMBAFCEBBJMHNEPCAKFAIAINHCKOAIKICFCPKHGNHANAKIDGIAPPKEJFJOAODDPAJAPECAACFPCKJENHHCGNMFCKGMADBPCAENLDDBACGAKOAAHICHGIAKFNBPNEPEAOAOOOMANBNPOOOJFICKEJACIJKBPCFEFCAOCBMJNDJKFGFAANDOHBNPIDKEAEMIAAIAGBKEJKNNMDHEPEMKOFMCKCHIMJEMCCAOMIFANFGDADJLLANACEHGAEIIBCLGDMAOLPNAEIHPOPPAKIDFIKNPGAFPAOMMGADANEFHJCGEJGJGDLAAKONAHIEBOCFHDIKMLFCCEKOCACHPMAFDDGDNPBLIBNJAHNNFDPNOGFOBNINAEAFMJOAAEFIGDCIFDPOEDOHIBMEBFNKACGKEMPACJCLBOICAHOKKJOAKIBIBAFMEDAFOEEMGNAPJOOMHCICBNNHHEAMNMPHEHCFHPBMGFHGFHEBFBFKFCMHIGJHOAKIGBAFNGDFNABKMHHMIKFEHEFKBHCMJOIMENIADNNMJPMFNOODAJOCMLBAHEBHAOKJCNINMMBMOCBGEKOEAFINCECAOKJOODKLAMPKCHFNKHBKCHCEECFAMKLIAEFIACIKFBKOACEPIANFNKPMHNIAKNODAIPOBAEAEAJNNFBMAODCKAHEGKAEMIABJEINOFOAALMHOCHAFIIJNFFCOCANMLFNACKGFEOLPHBMNPADCANJMAENAFANAOKFAAOKBAPBIEAEFGBKJGEPMKFCGMKKKOAFICDAHHMGAHHBFCPAEMIAHCEKGNHMKFKFEIOCOHEIJAHAONBEAIAAEMCBJECMKIPAEIDPAFBCJBMAMPJAJEADHKKFACIDMAFAJEBHEMPJCFEOMEFMICBNDKGLAIIHIGBAFEDCCMLJFGECAGPHHAKPICCNBNHADHIEAHBDFNEJCFOMOCDMCOCPBHPIDKHEKNKLBIGLCNCNJAOMKBMACIKDAHLJEPFAKDPIAIGPDFIIEEMAKONIJIFOEFBOAMMKEPLAKJBIFHIHICFADKAOAPNFMKDECBIHKIBMHIDECAMEJPJMDMAAEPNJMAPEGKANFMCBGMALICDLDFCACOCCADDGHNCLFPACMAAHHECBDDDKBDDADDMEAPIJNNMLADAHDPONFPIEAHDDIEHADOAOAHLBEOHGAMIHCBENFHFFKFJIECNDFBLMPGMICAHDGDAHMDHFFCMDIDCPMDJBBDHBMMLGDCHJANFBEGOAMJHFDANCAGAOGLDAIPOCHOGFEPIDOPAMPEBBPCIBILHKNDMKKOOCHABOGOJNONOFAIBOIKIOIBKAOKHOAIBFJAGLPDAKFHADIMBAPHOOIOHOHOCKNHAJMAHFCFJNOJDMAIFPEAALAMAHKOAAFIAJKFPCFAAEMLAHBCBJDAGCAMAMOLMACIAOCDOAGPHOIFIFIHOHLMEFCFEHAJAMHAINPDBKIKPNPFAOACCONMJEJBEKFMHAINMFGDIICCDKADAMIAMOLMAAAFEEDGNNOPJICEBKICJMAOIOEJBEDFPBOAGKAPMNIAMHFMGBHOEKKIICIIDJEFCJIFGMAJBKCADPIDCJFMPNNCAHAAKEEAPECKAFKLDMNIHAKKHNGIICMMHFHCIKKNILIHOADBEKADMDDOAHJFICKCMACIKCMPBDEDCAOLKMJNMNMFOFAINDOHONPINBDAJBMHADAJOFHJAFGKKPHJIDHEMHPFHIBOEKNINAFGFFAGGANAMKAFAHKHCAPICMOEFFPJBDOLFJPIPMPKPKAGINEPFAOJDLHAJCNCANDICOADPFDJHHGPLAANCNAHJEDOHCHAIKMDOCCENFDAGPPNAFDMMDNPBFAOGAEOIECOMMOHNLDCBFACHHDHGAHPINDCHOIBCAKGFOJIJMPODNHHIDKFDCHIEJANLAIFAHCCPKFHADPHOJNMHAFJHFAGPKMFGBEPNDCPDMHHAAODIOHEHLMGBCDEBBEMCDJNCOOHKAIIPCMHDAHBFKFJOCIGMKDOOPKNICAMBKHAIGHMJGAMCAFIBNJGAEDAJMIHACNKBOKOEKNOOLIFIDOHEKHNIPPAMIIMJKAENOIJEGKKAHFNIAKOBHAIAEFMOKHAECAOFHHAOBHKJFCPIFOHGMGNMMEMCEFCEEEAOHOBHOOMNHAPCHDNCAFHEMADIOOFPHFIAOHGLHIOEMJLIOMKBAIEJACHGHMCFKACPBIACDBNGCGPOMMHCFCEDODAIADNAKKIHDIICCAFDOIMAJBFPKPMMJIAHLAAAHNGAAFABFJALOIPJIHJDKEFAHFAKEGIHAODNNAOBKIMJJANEJNFLALGPAHDLECFPOCCEKIHPIAANINPJADAHFAPNDLCNHAAHHMHEAHEOJCDGNJFHOOKDAIINAOOEMPGOANGIDAAGBGFICAEGMKNBNCCOPHHDABPFAOOGEAIHICHAECDFKACJMIACOCNHDGFOMMNGFCEMNEDEFDBHNKNMLAIDBMNCCHMOOMJPCIEIHPNOOJBOMNKKACAECOHMJKDHAOGDCAINPBDBFHGDMMBACEEGAECFLFKHKKIDHIIAGGFBOKGCANNJCAAOECHKJIBHAOJCKAECKBFNFHAMHMLNCFEPIDFFNAIGMCOEACKDBENAAIAANCHHKOHFDFHPIACPOCHCAFKGMFNPNDNOAHAICAPDONCEFJCHFKNOAGIGFMAKEPOJFKFFDNIBLOCOHECCAKNFIAIPIDFKOAIMFCCPNAHJEEMKGCMEDAIAMHAHDCMLAAJECJPHAHPPHNMIBIKEFEIBOGONPEKHKNBIADHCFJPFFHDPCFEHNANFHAAGMDECDAPBNAABFAAFCBFDEIMNFHCFOGFLODDHIIJEKAPFKKAPOGKJIPLKAODNJAOMKLDOPCNHMMAMMCEOHJMHMCFEDFGBMPMJIKJKDJMPOABHAOJBPPFCCIBGAAGHOJAKHCMHEHJCMMKECEEFMJFPDIPGMAOJKCJEEDFIIABMKFPLAKNBKNMDEIAHEFNBOBGEOGANKHFAKAEIHIAFHKFGOAFNDHKONPDKFPOIKEDODALEMHJENFMLGEBCKAKFOIAGEDOIDICONFKAKOGEEIKGBAGIAEEKAJJAKCMPJHLCKAKFHIAECCOKMAFIHFKANFGFBGHCKACFMDMFACPKLOHKCPDHAKHEJAIKPPONONJIHKMCOHINAMHMHNDHAMCMFACHLAMLMNOCAKBPOAIKMINAFDBADKAGDPIBEOODMEMIAEEFMJOJCEAMLHJAEMMGDJEGEMAMLIAJFMNNKACEFKECFFKBNNCBHAALDAFLNADGKEKFACJFJNKMFACIHKFJAHIPEAFKCIDNDDFFKEHKNMBLIMOMBAOBBMACCEKFOADIMDDDACJOKPFGDHHGNNGICAOCHDFMAGEGAOIBFAIIHPDMENAPMEADBEBFHKHHIEFHAFMIMAMNCECOJGDHMKGJFEINPCMJDAOEAONDAJIIHMDIEGHPKAHMFIAFFCAOBOMAKFEENINCJICLJHPHMNNPDEAJPAACMOBJNOKANAIHAIEOBEPJHPJOMFCEOMALIJCAKAJKAIAKLEADLADJNOPMAAIECFKCFPJCODOHDIDFGNADIJPAENNPAJAPHLKJCICIFNBNKGOEBFAFHMIADCJHFHHCLPAKBAGJOHLFAIFLHHMCDHBCAKJKDAICFBNHJOAAKDPOOCPIKENNGAKAFMLHAGEEJIADENNAMNIABEOBOCOHBHNNMHHGCEHNMMEPMGGBKMEKFICAGHKDNADKADPJNAPMLOCIOADKMFEAALMCPBAJOGHAEKJFFBIAAAAIDALJFHKPAAFKODFKBCBGONEFKIABBHAFDPPJFMDHDNEEGLMMKAEEDKNKAHIKGLOIGNKIEAGFFOJNBANKOAEADCJKAHKHMCNKMOKAFMIBEGCCNICEJAHECKPHNKKPFECHAKKHKAIFKIAJCCAMEKNANFGJKANFAAFELIHAAHKFKAHDAFCEEFAHMNHFHEAOHGOLPENIAEBFMJOCEANHDACACJNPAHPNADKBCDPICFMBDHAOKBEPHAOBADFGNAHMLIMKEINCAHMLKJHFADKPMICIDNDMKDOPFECDDAMHDAHMNDALJEKICCDIMMGNMCECGMAOAAHANCBGNGHAGNAAJHMAOAEFCILLGBDFDGBHKICFFIHONDOJEHMICAJKHHAAABNEBICADAHEOHJAFNAKNCKAEDIFMBPCJCNCBADACHJMAHFFLGFBMCIGMMJFKECACCFKEGCGKAKFFIABGDNGMCNONAFACAAHNHKCLJBIAFCPEAGFDMKOKHKCMFGFDEGANBJPJPPLANJIDAAEHHOPDHBIKMCACCEGNEEOBPJJFDKGDNPJEIKBMCAIFAAOKGAIBFKNNAIIFAOMNGABIOEMJJOBNDBLAAHHIPDOMKMHKAOBKIAPIIMMMAKEAKCFNAKKHFAGIEEJADPMMAECPFCPGAJHHMDKAHEBMANHAOIADKEEEPIIINHCHIMHMAOCOCALHNAIEGHJNFCEFAMCGOANLBPAEOPGEJIEGDAOKGAAKKFPFICCFDFILIANDKJHKPKCBHAFFAFAEEGLNBOHIEACEHCJKEMAHIBLBDEHAOJBNMAPNACAHFDAGAPHCADCNHAPKEHHPBAFAOOPEAICOHAEHPOJNAIHBAADGNOBECHOBFHIKNNOHPAGBILAOCDFOIHGHNDHPICPDDGMKDHAFDFIEAAMKNGCAKAEEJFEEKIGFAGFKMAGCACKEADHKFDCAKNBLJADLOHJMKBLEEICKPNJCACAANLPAJAEJPDAIAPENAEAFAACJLACDGJAOOMMFOIFEBAACHJJKBKMHIDFFCCIJOLKOMCBNICNOCFFAIBGMAMPKCAKECKHHIKIHCNKKFHCFMABPAMAHHCDAFFECJKBNPCCOMNNDOCGNFALFEKAENNIMJAACPONOCBIDMDBMPEONBAIJKHAFAKOKMAGOBMANIFCMDKNKCJCIAKGNBBIAOHAEAIHOCHCOGAFNMELFACCCEMIHPPCNNDBDAAMEFMECALEAFKJAJNCKINGDGDACICKFHEIGAKPONDIADHLFJPPCEJAEGJLAIOJNAELMOOPOHAIKMNACCEBNIAJBPCAFDEGDNPHEIHAEABHMCBPNCHDAMDBNCIPNOGCMAICNOHNABGHAMEKEACOGAMDGNHCAKMCOAIEHANIMDKADKIDDPIFHNOGKEOIAENHMJOIGKOCNHDIAMKFDAEFHBAMNHBAKAKMHIAHINANIINAIFHKKEGFEKKNPHLCOHABCIHCJEEHOJDJMOEEAEIFGJKDHCDIFADHKGAJBHNDKIFOFAJDKGAAECMDLAJCANEKFAABFCNLNEKADOLDMPNAFGIJDNEHAFMCFAGEHJDEGIIHAFJHKAGMKCHFODJHAKOADAIOANMIHFMEDKPOHPICNBFIENHAAKFCFACNOBKDOADIMNJEACALJPACDIFAIKICKEKDKCNKBGDACOEIFHOFOBHABOJFAFOBOAGCPGKNFBAINMDLEOCOKPHNDIJFADPCKADOGAAHHIEJEDFPOBPHCDNOBBMHAOHBEAIINONDKIDAFCPJOGHLDLANPIMAOACHOIJGPJOAGANNAANDNAJLGAACDPPANMOMDAEPFDFNNABNDHHFNPDKACKJCENIDABCMDJFNCMEEEOCKAIBOIAFDBNDBIAANFFAKOGBAEDAEAOPBNKFADGNKMMCHIJCAFMBOJGFANAMPIDAMNLJKEOIAMDHBICPDMKNKDCMNMAHBOPJMNLOEEAJOBKGFEEIAOOFMAIAMNCFIANDCFGGADGMLMHOBCHFMALICEAFEMEODACBDCIFNPHAGHBHCDAKOAHDCFABCDNHKAEGDHMAADPAHCHBOIIFFAJFKGANMMDNCCIPNMDAKAENFLOOOAKIBKAPANIIFNALOJCJMFLIAEAFCEANLMAADAGFFHJNGFMKCJBEFOMBAGILDFNKGECAMCDCMCHBJGMECAMEKDBAAKHJJBNBAIGAHFIFKHAFLPMNOJBCKMADAICCGIBKJIOMAFEHOAGCCFEPOMAJDBOFBJMGJMMIDKKCFANMKMANJLIEMHMEMFPOCEGJNNAIEEEAIEBCMEOKMOHHFIHFNDPFOOPJKOPBBNOCNOKLOAICDFKHGIAIAODBOAICOKNHAAHADKJHNDCDJPDDLHKPOAECDIAIBCCDFGEHNONJFAIEKHNDNAOADOEEFHIHOFACNJAANAPNAAAHBGFJMADNDHELNPDBKNADIEKADAGAMHJJOGFDHIAGMOOHKCECJNECEOFJMKIINEILBAHKOAGFAAGDNAAKPIABAOOJKABBNIAEBFKHDCAIAMONKJEHHLKMJADCMDFCACHEIDABGGKAMMFMFEEHHAKFLAGIMHMHACMOFGDPKHDENNPMCAOAILJDFJJPOMLCAIELOHKIFCCICAKPMHAOFDANFIOAHNOOKFOGIDCKOGLHKOAFFIELLPDFHEEHAKPAIAIMLIHINHPFKOJBCIIECOHKOEFFAKKFIAIJIJFPDENMAKOFIJIPMIMBLBDBMNFBMBGMAP'
# b = 'KEOIAKDKNDKHKILOMPPBLBMNDKMBAGEE'
# c = 'KIHICKDKFHKHKCBAMAJBNBMNBGMBANBA'
# d = 'MAKBNBMCGKMBDBKKMBPBBBMMENMBBEKE'
#
# '''
# K I K D K K H K
# 1 2 3 4 5 6 7 8
# M B B M M M B B
# '''
#
#
# tab_1 =  [5, 8, 1, 2, 4, 7, 6, 3] # KK KI DH KK
# tab_2 =  [5, 8, 1, 7, 4, 2, 6, 3] # KK KH DI KK
# tab_3 =  [5, 8, 4, 2, 1, 7, 6, 3] # KK DI KH KK
# tab_4 =  [5, 8, 4, 2, 6, 7, 1, 3] # KK DI KH KK
# tab_5 =  [5, 8, 4, 7, 1, 2, 6, 3] # KK DH IK KK
# tab_6 =  [5, 8, 4, 7, 6, 2, 1, 3] # KK DH KI KK
# tab_7 =  [5, 8, 6, 2, 4, 7, 1, 3] # KK KI DH KK
# tab_8 =  [5, 8, 6, 7, 4, 2, 1, 3] # KK KH DI KK
# tab_9 =  [8, 5, 2, 1, 7, 4, 3, 6] # KK IK HD KK
# tab_10 = [8, 5, 2, 4, 7, 1, 3, 6] # KK ID HK KK
# tab_11 = [8, 5, 2, 4, 7, 6, 3, 1] # KK ID HK KK
# tab_12 = [8, 5, 2, 6, 7, 4, 3, 1] # KK IK HD KK
# tab_13 = [8, 5, 7, 1, 2, 4, 3, 6] # KK HK ID KK
# tab_14 = [8, 5, 7, 4, 2, 1, 3, 6] # KK HD IK KK
# tab_15 = [8, 5, 7, 4, 2, 6, 3, 1] # KK HD IK KK
# tab_16 = [8, 5, 7, 6, 2, 4, 3, 1] # KK HK ID KK
#
# # Соответствия для словарей
# dict_1 =  {'KK': 'б', 'KI': 'о', 'DH': 'м', 'KK': 'б', 'NA': 'а'}
# dict_2 =  {'KK': 'б', 'KH': 'о', 'DI': 'м', 'KK': 'б', 'NA': 'а'}
# dict_3 =  {'KK': 'б', 'DI': 'о', 'KH': 'м', 'KK': 'б', 'NA': 'а'}
# dict_4 =  {'KK': 'б', 'DI': 'о', 'KH': 'м', 'KK': 'б', 'NA': 'а'}
# dict_5 =  {'KK': 'б', 'DH': 'о', 'IK': 'м', 'KK': 'б', 'NA': 'а'}
# dict_6 =  {'KK': 'б', 'DH': 'о', 'KI': 'м', 'KK': 'б', 'NA': 'а'}
# dict_7 =  {'KK': 'б', 'KI': 'о', 'DH': 'м', 'KK': 'б', 'NA': 'а'}
# dict_8 =  {'KK': 'б', 'KH': 'о', 'DI': 'м', 'KK': 'б', 'NA': 'а'}
# dict_9 =  {'KK': 'б', 'IK': 'о', 'HD': 'м', 'KK': 'б', 'AN': 'а'}
# dict_10 = {'KK': 'б', 'ID': 'о', 'HK': 'м', 'KK': 'б', 'AN': 'а'}
# dict_11 = {'KK': 'б', 'ID': 'о', 'HK': 'м', 'KK': 'б', 'AN': 'а'}
# dict_12 = {'KK': 'б', 'IK': 'о', 'HD': 'м', 'KK': 'б', 'AN': 'а'}
# dict_13 = {'KK': 'б', 'HK': 'о', 'ID': 'м', 'KK': 'б', 'AN': 'а'}
# dict_14 = {'KK': 'б', 'HD': 'о', 'IK': 'м', 'KK': 'б', 'AN': 'а'}
# dict_15 = {'KK': 'б', 'HD': 'о', 'IK': 'м', 'KK': 'б', 'AN': 'а'}
# dict_16 = {'KK': 'б', 'HK': 'о', 'ID': 'м', 'KK': 'б', 'AN': 'а'}
#
#
# def ex(tab, dict_):
#     d1 = calc_dict('бомб', b[0:16], tab)
#     d2 = calc_dict('а___', b[16:32], tab)
#     d3 = calc_dict('1___', d[0:16], tab)
#     d4 = calc_dict('____', d[16:32], tab)
#
#     dic = d1 | d2 | d3| d4| dict_
#
#     result = decode(shuffle(rm_noise(a), tab), dic)
#
#     # Записываем в файл
#     with open(output_file, 'a', encoding='utf-8') as f:
#         f.write(f"Permutation: {tab}\n")
#         f.write(f"Decoded Text: {result}\n\n")
#
# output_file = "results.txt"
#
# # Перебор всех подстановок и запись в файл
# with open(output_file, 'w', encoding='utf-8') as f:
#     f.write("Starting decoding...\n\n")
#
# for t in permutations(range(1, 9)):
#     ex(list(t), dict_1)
#
# print(f"Результаты сохранены в {output_file}")

# ex(tab_1, dict_1)
# ex(tab_2, dict_2)
# ex(tab_3, dict_3)
# ex(tab_4, dict_4)
# ex(tab_5, dict_5)
# ex(tab_6, dict_6)
# ex(tab_7, dict_7)
# ex(tab_8, dict_8)
# ex(tab_9, dict_9)
# ex(tab_10, dict_10)
# ex(tab_11, dict_11)
# ex(tab_12, dict_12)
# ex(tab_13, dict_13)
# ex(tab_14, dict_14)
# ex(tab_15, dict_15)
# ex(tab_16, dict_16)
'''
#     # Записываем в файл
#     with open(output_file, 'a', encoding='utf-8') as f:
#         f.write(f"Permutation: {tab}\n")
#         f.write(f"Decoded Text: {result}\n\n")
#
# output_file = "results.txt"
#
# # Перебор всех подстановок и запись в файл
# with open(output_file, 'w', encoding='utf-8') as f:
#     f.write("Starting decoding...\n\n")
#
# for t in permutations(range(1, 9)):
#     ex(list(t), dict_1)
#
# print(f"Результаты сохранены в {output_file}")
ты должен будешь менять цифры на буквы, которые соответствуют этому словарю letters_numbers_pairs = {
    'K': ['1', '3', '5', '6', '8'],  # K соответствует этим цифрам
    'I': ['2'],                      # I = 2
    'D': ['4'],                      # D = 4
    'H': ['7']                       # H = 7
}

по той перестановке, которая указана в Permutation

СМОТРИ ШАГИ

1) смотрим на Permutation: [5, 8, 1, 2, 4, 7, 6, 3]
2) смотрим какая буква соответствует паре из Permutation в letters_numbers_pairs
3) заменяем на соответствующие буквы т.е если пара 5,8 Это будет KK, если 1,2 это будет KI, 4, 7 - DH, 6, 3 - KK
'''

from itertools import permutations
from textwrap import wrap

# --- Словарь соответствия букв и позиций ---
letters_numbers_pairs = {
    'K': ['1', '3', '5', '6', '8'],  # K соответствует этим цифрам
    'I': ['2'],  # I = 2
    'D': ['4'],  # D = 4
    'H': ['7']  # H = 7
}

# --- Оригинальные словари расшифровки ---
dict_1 = {'KK': 'б', 'KI': 'о', 'DH': 'м', 'KK': 'б', 'AN': 'а'}
dict_2 = {'KK': 'б', 'KH': 'о', 'DI': 'м', 'KK': 'б', 'NA': 'а'}
dict_3 = {'KK': 'б', 'HD': 'о', 'IK': 'м', 'KK': 'б', 'NA': 'а'}
dict_4 = {'KK': 'б', 'ID': 'о', 'HK': 'м', 'KK': 'б', 'AN': 'а'}


# --- Функция для поиска буквы по цифре ---
def find_letter_by_number(number):
    for letter, numbers in letters_numbers_pairs.items():
        if str(number) in numbers:
            return letter
    return '?'  # Если цифра не найдена


# --- Функция перестроения словаря по Permutation ---
def remap_dict(permutation, original_dict):
    remapped = {}

    # Формируем пары (0,1), (2,3), (4,5), (6,7) из Permutation
    for i in range(0, len(permutation), 2):
        a, b = permutation[i], permutation[i + 1]

        # Находим буквы для текущей пары
        letter_a = find_letter_by_number(a)
        letter_b = find_letter_by_number(b)

        # Создаём новый ключ для словаря (например, KK, KI)
        new_key = f"{letter_a}{letter_b}"

        # Берём значение из исходного словаря (или по умолчанию '?')
        value = original_dict.get('KK', '?')  # Если ключ отсутствует, берём 'KK' как стандарт

        # Заполняем новый словарь
        remapped[new_key] = value

    return remapped


# --- Функции для расшифровки текста ---
def rm_noise(s):
    places = [3, 4, 6, 10, 11, 13, 14, 15]
    a = wrap(s, 16)
    r = ''
    for w in a:
        for p in places:
            r += w[p]
    return r


def shuffle(s, table):
    a = wrap(s, 8)
    r = ''
    for w in a:
        for i in table:
            r += w[i - 1]
    return r


def decode(s, table):
    a = wrap(s, 2)
    r = ''
    for w in a:
        if w in table:
            r += table[w]
        else:
            r += '?'
    return r


def calc_dict(sample, encoding, table):
    t = rm_noise(encoding)
    tnew = wrap(shuffle(t, table), 2)
    s = wrap(sample, 1)
    d = {}
    for i in range(len(s)):
        d[tnew[i]] = s[i]
    return d


a = 'AJNOLJKODNNIKHBKMHPAIEFKJBNGCMEPFEKNEMADIHFJPAHLMCJAOEFIBHAGEFFCAADCHAFNBMMGOBFEDHLIAPDMFCKDCIBHAKMOCJMNFDEEACCGHNDBGHAOEAEAINGBNAIACAHKDGADIDIFMKDNDEADJBFJPDEJOFGOBEADEMOAHNJEKLNCGIFKBHMGIAMEAHHOEAENNOOJOCEBKEAALINHIPAOFBLAKMCIMICFBCKHGHDHKILAIIHDCJAHHGADMAGJLCNAKPAAADEBAANIHJEFBFKBGLKOBHBPEMAOBFJAIDJIOCHABIDFOHNPGDGFCBNAFCAACENAJAJFOHHOCIMOMBNCIIIINIAICAHCBJKFHKPDFDOIMNMDFLOCPDAEDKNHFPKACFHIAKNGKEPGHCOOHEFIIOGAOADCOINMKIMOEPGDMGAAFCOMCCAOEHINOIIIEIHDPJKFPBHNKNOAFCOEGKAOBNINOONCDIFNAFMGANBEBBOACMBEFNAMBAFJHBDJFFABNCDAMMKDIFEFFEKAIEHIANMMAHIEDJAAJBMAJDKBNHKAMAHNCOADAPNOMEANEEADOKFJPDEFKDNAEIODJDAEHLEBNKGGBOKMECFICOFNKNBJGKAMIJEAENECMNLPMCAFONDAMFHPNMJDIADKGMDPIHPINMAICAHMICKFCJGAJGCAHACAGCADJHBBHMECBFMANACEAHGDEKKAFBDCNBNPHLMCNOPMAAFABNBGAJFMFKEILMADDGOJPNEJBLBJAPADFMEAHHPEFHNPCGKKGCDIIBKODLKFDHFKAHHMIHPFODBAOODENHAJJEMHDMKFJPMFODHEAGAHDEAGKHKFLGFINPPDCJBIKIAAANOAAHNOOIBHKICNKBCHALEHKCEAGIADILNJHHDMOJBGDEADKBNAHAHFHENIIFFAEDKGAMLEAEBGJJAMMAFAEPNNKKFAHIMNFCACAFODMPNPPCNDHBDADAMCDGJEGJAOEDMAIEGMOMACPIMKDCMCIHOAMJKACCHOECAFIPOLOGOOGIHFPMOHGADCHDONBFAFIBFAGEGCINHFJEKAMDHIAOKHHACODHAAJIOAJFJPOFBIPIFCPJKGHDACHEAAFHBHGAADFPNJOJFJGIOKPJAIIELCCIGCPHMAOKKEAGFEOCMACNAMENFAELBKFLGAGGLHPENDFFGKDEGILHACKDOAHGGKPGOCFCEMJKMBEKCOKGMACIHNFBAHAHEPAFCPBAMMEJDECHDFOBFADIHNLDNHOCHEEPGOEBDFGOOPGBKEAAGIAAOPDNOICFAHDHJEJHCCDNMHIAMHOHMJHIONBFAIAHGKGMDMFPCAJCBFABFLEHFIMBKAHCKKANJMOEPAOIDFFFNPAOBJHGONEHAMNKFACDCPMOCNAEOKDIONINOBFAMNOGNCILBAHLIICODABHFFDGAGNBLDHJFKJFKMPGKIECEMENCJGBONLCAIAGDHFMDAHMHEBHAFJGPCACOFPJOODPHINLMFMPAGLEFOKPFMOEDLHDOCBFKAOCMIAHDINKMGFOMMBAFCEBBJMHNEPCAKFAIAINHCKOAIKICFCPKHGNHANAKIDGIAPPKEJFJOAODDPAJAPECAACFPCKJENHHCGNMFCKGMADBPCAENLDDBACGAKOAAHICHGIAKFNBPNEPEAOAOOOMANBNPOOOJFICKEJACIJKBPCFEFCAOCBMJNDJKFGFAANDOHBNPIDKEAEMIAAIAGBKEJKNNMDHEPEMKOFMCKCHIMJEMCCAOMIFANFGDADJLLANACEHGAEIIBCLGDMAOLPNAEIHPOPPAKIDFIKNPGAFPAOMMGADANEFHJCGEJGJGDLAAKONAHIEBOCFHDIKMLFCCEKOCACHPMAFDDGDNPBLIBNJAHNNFDPNOGFOBNINAEAFMJOAAEFIGDCIFDPOEDOHIBMEBFNKACGKEMPACJCLBOICAHOKKJOAKIBIBAFMEDAFOEEMGNAPJOOMHCICBNNHHEAMNMPHEHCFHPBMGFHGFHEBFBFKFCMHIGJHOAKIGBAFNGDFNABKMHHMIKFEHEFKBHCMJOIMENIADNNMJPMFNOODAJOCMLBAHEBHAOKJCNINMMBMOCBGEKOEAFINCECAOKJOODKLAMPKCHFNKHBKCHCEECFAMKLIAEFIACIKFBKOACEPIANFNKPMHNIAKNODAIPOBAEAEAJNNFBMAODCKAHEGKAEMIABJEINOFOAALMHOCHAFIIJNFFCOCANMLFNACKGFEOLPHBMNPADCANJMAENAFANAOKFAAOKBAPBIEAEFGBKJGEPMKFCGMKKKOAFICDAHHMGAHHBFCPAEMIAHCEKGNHMKFKFEIOCOHEIJAHAONBEAIAAEMCBJECMKIPAEIDPAFBCJBMAMPJAJEADHKKFACIDMAFAJEBHEMPJCFEOMEFMICBNDKGLAIIHIGBAFEDCCMLJFGECAGPHHAKPICCNBNHADHIEAHBDFNEJCFOMOCDMCOCPBHPIDKHEKNKLBIGLCNCNJAOMKBMACIKDAHLJEPFAKDPIAIGPDFIIEEMAKONIJIFOEFBOAMMKEPLAKJBIFHIHICFADKAOAPNFMKDECBIHKIBMHIDECAMEJPJMDMAAEPNJMAPEGKANFMCBGMALICDLDFCACOCCADDGHNCLFPACMAAHHECBDDDKBDDADDMEAPIJNNMLADAHDPONFPIEAHDDIEHADOAOAHLBEOHGAMIHCBENFHFFKFJIECNDFBLMPGMICAHDGDAHMDHFFCMDIDCPMDJBBDHBMMLGDCHJANFBEGOAMJHFDANCAGAOGLDAIPOCHOGFEPIDOPAMPEBBPCIBILHKNDMKKOOCHABOGOJNONOFAIBOIKIOIBKAOKHOAIBFJAGLPDAKFHADIMBAPHOOIOHOHOCKNHAJMAHFCFJNOJDMAIFPEAALAMAHKOAAFIAJKFPCFAAEMLAHBCBJDAGCAMAMOLMACIAOCDOAGPHOIFIFIHOHLMEFCFEHAJAMHAINPDBKIKPNPFAOACCONMJEJBEKFMHAINMFGDIICCDKADAMIAMOLMAAAFEEDGNNOPJICEBKICJMAOIOEJBEDFPBOAGKAPMNIAMHFMGBHOEKKIICIIDJEFCJIFGMAJBKCADPIDCJFMPNNCAHAAKEEAPECKAFKLDMNIHAKKHNGIICMMHFHCIKKNILIHOADBEKADMDDOAHJFICKCMACIKCMPBDEDCAOLKMJNMNMFOFAINDOHONPINBDAJBMHADAJOFHJAFGKKPHJIDHEMHPFHIBOEKNINAFGFFAGGANAMKAFAHKHCAPICMOEFFPJBDOLFJPIPMPKPKAGINEPFAOJDLHAJCNCANDICOADPFDJHHGPLAANCNAHJEDOHCHAIKMDOCCENFDAGPPNAFDMMDNPBFAOGAEOIECOMMOHNLDCBFACHHDHGAHPINDCHOIBCAKGFOJIJMPODNHHIDKFDCHIEJANLAIFAHCCPKFHADPHOJNMHAFJHFAGPKMFGBEPNDCPDMHHAAODIOHEHLMGBCDEBBEMCDJNCOOHKAIIPCMHDAHBFKFJOCIGMKDOOPKNICAMBKHAIGHMJGAMCAFIBNJGAEDAJMIHACNKBOKOEKNOOLIFIDOHEKHNIPPAMIIMJKAENOIJEGKKAHFNIAKOBHAIAEFMOKHAECAOFHHAOBHKJFCPIFOHGMGNMMEMCEFCEEEAOHOBHOOMNHAPCHDNCAFHEMADIOOFPHFIAOHGLHIOEMJLIOMKBAIEJACHGHMCFKACPBIACDBNGCGPOMMHCFCEDODAIADNAKKIHDIICCAFDOIMAJBFPKPMMJIAHLAAAHNGAAFABFJALOIPJIHJDKEFAHFAKEGIHAODNNAOBKIMJJANEJNFLALGPAHDLECFPOCCEKIHPIAANINPJADAHFAPNDLCNHAAHHMHEAHEOJCDGNJFHOOKDAIINAOOEMPGOANGIDAAGBGFICAEGMKNBNCCOPHHDABPFAOOGEAIHICHAECDFKACJMIACOCNHDGFOMMNGFCEMNEDEFDBHNKNMLAIDBMNCCHMOOMJPCIEIHPNOOJBOMNKKACAECOHMJKDHAOGDCAINPBDBFHGDMMBACEEGAECFLFKHKKIDHIIAGGFBOKGCANNJCAAOECHKJIBHAOJCKAECKBFNFHAMHMLNCFEPIDFFNAIGMCOEACKDBENAAIAANCHHKOHFDFHPIACPOCHCAFKGMFNPNDNOAHAICAPDONCEFJCHFKNOAGIGFMAKEPOJFKFFDNIBLOCOHECCAKNFIAIPIDFKOAIMFCCPNAHJEEMKGCMEDAIAMHAHDCMLAAJECJPHAHPPHNMIBIKEFEIBOGONPEKHKNBIADHCFJPFFHDPCFEHNANFHAAGMDECDAPBNAABFAAFCBFDEIMNFHCFOGFLODDHIIJEKAPFKKAPOGKJIPLKAODNJAOMKLDOPCNHMMAMMCEOHJMHMCFEDFGBMPMJIKJKDJMPOABHAOJBPPFCCIBGAAGHOJAKHCMHEHJCMMKECEEFMJFPDIPGMAOJKCJEEDFIIABMKFPLAKNBKNMDEIAHEFNBOBGEOGANKHFAKAEIHIAFHKFGOAFNDHKONPDKFPOIKEDODALEMHJENFMLGEBCKAKFOIAGEDOIDICONFKAKOGEEIKGBAGIAEEKAJJAKCMPJHLCKAKFHIAECCOKMAFIHFKANFGFBGHCKACFMDMFACPKLOHKCPDHAKHEJAIKPPONONJIHKMCOHINAMHMHNDHAMCMFACHLAMLMNOCAKBPOAIKMINAFDBADKAGDPIBEOODMEMIAEEFMJOJCEAMLHJAEMMGDJEGEMAMLIAJFMNNKACEFKECFFKBNNCBHAALDAFLNADGKEKFACJFJNKMFACIHKFJAHIPEAFKCIDNDDFFKEHKNMBLIMOMBAOBBMACCEKFOADIMDDDACJOKPFGDHHGNNGICAOCHDFMAGEGAOIBFAIIHPDMENAPMEADBEBFHKHHIEFHAFMIMAMNCECOJGDHMKGJFEINPCMJDAOEAONDAJIIHMDIEGHPKAHMFIAFFCAOBOMAKFEENINCJICLJHPHMNNPDEAJPAACMOBJNOKANAIHAIEOBEPJHPJOMFCEOMALIJCAKAJKAIAKLEADLADJNOPMAAIECFKCFPJCODOHDIDFGNADIJPAENNPAJAPHLKJCICIFNBNKGOEBFAFHMIADCJHFHHCLPAKBAGJOHLFAIFLHHMCDHBCAKJKDAICFBNHJOAAKDPOOCPIKENNGAKAFMLHAGEEJIADENNAMNIABEOBOCOHBHNNMHHGCEHNMMEPMGGBKMEKFICAGHKDNADKADPJNAPMLOCIOADKMFEAALMCPBAJOGHAEKJFFBIAAAAIDALJFHKPAAFKODFKBCBGONEFKIABBHAFDPPJFMDHDNEEGLMMKAEEDKNKAHIKGLOIGNKIEAGFFOJNBANKOAEADCJKAHKHMCNKMOKAFMIBEGCCNICEJAHECKPHNKKPFECHAKKHKAIFKIAJCCAMEKNANFGJKANFAAFELIHAAHKFKAHDAFCEEFAHMNHFHEAOHGOLPENIAEBFMJOCEANHDACACJNPAHPNADKBCDPICFMBDHAOKBEPHAOBADFGNAHMLIMKEINCAHMLKJHFADKPMICIDNDMKDOPFECDDAMHDAHMNDALJEKICCDIMMGNMCECGMAOAAHANCBGNGHAGNAAJHMAOAEFCILLGBDFDGBHKICFFIHONDOJEHMICAJKHHAAABNEBICADAHEOHJAFNAKNCKAEDIFMBPCJCNCBADACHJMAHFFLGFBMCIGMMJFKECACCFKEGCGKAKFFIABGDNGMCNONAFACAAHNHKCLJBIAFCPEAGFDMKOKHKCMFGFDEGANBJPJPPLANJIDAAEHHOPDHBIKMCACCEGNEEOBPJJFDKGDNPJEIKBMCAIFAAOKGAIBFKNNAIIFAOMNGABIOEMJJOBNDBLAAHHIPDOMKMHKAOBKIAPIIMMMAKEAKCFNAKKHFAGIEEJADPMMAECPFCPGAJHHMDKAHEBMANHAOIADKEEEPIIINHCHIMHMAOCOCALHNAIEGHJNFCEFAMCGOANLBPAEOPGEJIEGDAOKGAAKKFPFICCFDFILIANDKJHKPKCBHAFFAFAEEGLNBOHIEACEHCJKEMAHIBLBDEHAOJBNMAPNACAHFDAGAPHCADCNHAPKEHHPBAFAOOPEAICOHAEHPOJNAIHBAADGNOBECHOBFHIKNNOHPAGBILAOCDFOIHGHNDHPICPDDGMKDHAFDFIEAAMKNGCAKAEEJFEEKIGFAGFKMAGCACKEADHKFDCAKNBLJADLOHJMKBLEEICKPNJCACAANLPAJAEJPDAIAPENAEAFAACJLACDGJAOOMMFOIFEBAACHJJKBKMHIDFFCCIJOLKOMCBNICNOCFFAIBGMAMPKCAKECKHHIKIHCNKKFHCFMABPAMAHHCDAFFECJKBNPCCOMNNDOCGNFALFEKAENNIMJAACPONOCBIDMDBMPEONBAIJKHAFAKOKMAGOBMANIFCMDKNKCJCIAKGNBBIAOHAEAIHOCHCOGAFNMELFACCCEMIHPPCNNDBDAAMEFMECALEAFKJAJNCKINGDGDACICKFHEIGAKPONDIADHLFJPPCEJAEGJLAIOJNAELMOOPOHAIKMNACCEBNIAJBPCAFDEGDNPHEIHAEABHMCBPNCHDAMDBNCIPNOGCMAICNOHNABGHAMEKEACOGAMDGNHCAKMCOAIEHANIMDKADKIDDPIFHNOGKEOIAENHMJOIGKOCNHDIAMKFDAEFHBAMNHBAKAKMHIAHINANIINAIFHKKEGFEKKNPHLCOHABCIHCJEEHOJDJMOEEAEIFGJKDHCDIFADHKGAJBHNDKIFOFAJDKGAAECMDLAJCANEKFAABFCNLNEKADOLDMPNAFGIJDNEHAFMCFAGEHJDEGIIHAFJHKAGMKCHFODJHAKOADAIOANMIHFMEDKPOHPICNBFIENHAAKFCFACNOBKDOADIMNJEACALJPACDIFAIKICKEKDKCNKBGDACOEIFHOFOBHABOJFAFOBOAGCPGKNFBAINMDLEOCOKPHNDIJFADPCKADOGAAHHIEJEDFPOBPHCDNOBBMHAOHBEAIINONDKIDAFCPJOGHLDLANPIMAOACHOIJGPJOAGANNAANDNAJLGAACDPPANMOMDAEPFDFNNABNDHHFNPDKACKJCENIDABCMDJFNCMEEEOCKAIBOIAFDBNDBIAANFFAKOGBAEDAEAOPBNKFADGNKMMCHIJCAFMBOJGFANAMPIDAMNLJKEOIAMDHBICPDMKNKDCMNMAHBOPJMNLOEEAJOBKGFEEIAOOFMAIAMNCFIANDCFGGADGMLMHOBCHFMALICEAFEMEODACBDCIFNPHAGHBHCDAKOAHDCFABCDNHKAEGDHMAADPAHCHBOIIFFAJFKGANMMDNCCIPNMDAKAENFLOOOAKIBKAPANIIFNALOJCJMFLIAEAFCEANLMAADAGFFHJNGFMKCJBEFOMBAGILDFNKGECAMCDCMCHBJGMECAMEKDBAAKHJJBNBAIGAHFIFKHAFLPMNOJBCKMADAICCGIBKJIOMAFEHOAGCCFEPOMAJDBOFBJMGJMMIDKKCFANMKMANJLIEMHMEMFPOCEGJNNAIEEEAIEBCMEOKMOHHFIHFNDPFOOPJKOPBBNOCNOKLOAICDFKHGIAIAODBOAICOKNHAAHADKJHNDCDJPDDLHKPOAECDIAIBCCDFGEHNONJFAIEKHNDNAOADOEEFHIHOFACNJAANAPNAAAHBGFJMADNDHELNPDBKNADIEKADAGAMHJJOGFDHIAGMOOHKCECJNECEOFJMKIINEILBAHKOAGFAAGDNAAKPIABAOOJKABBNIAEBFKHDCAIAMONKJEHHLKMJADCMDFCACHEIDABGGKAMMFMFEEHHAKFLAGIMHMHACMOFGDPKHDENNPMCAOAILJDFJJPOMLCAIELOHKIFCCICAKPMHAOFDANFIOAHNOOKFOGIDCKOGLHKOAFFIELLPDFHEEHAKPAIAIMLIHINHPFKOJBCIIECOHKOEFFAKKFIAIJIJFPDENMAKOFIJIPMIMBLBDBMNFBMBGMAP'
b = 'KEOIAKDKNDKHKILOMPPBLBMNDKMBAGEE'
c = 'KIHICKDKFHKHKCBAMAJBNBMNBGMBANBA'
d = 'MAKBNBMCGKMBDBKKMBPBBBMMENMBBEKE'


# --- Функция расшифровки с учётом Permutation ---
def ex(tab, permutation):
    # Динамическое создание словаря на основе Permutation
    updated_dict_1 = remap_dict(permutation, dict_1)
    updated_dict_2 = remap_dict(permutation, dict_2)
    updated_dict_3 = remap_dict(permutation, dict_3)
    updated_dict_4 = remap_dict(permutation, dict_4)

    d1 = calc_dict('бомб', b[0:16], tab)
    d2 = calc_dict('а___', b[16:32], tab)
    d3 = calc_dict('1___', d[0:16], tab)
    d4 = calc_dict('____', d[16:32], tab)

    # Объединяем все словари
    dic = d1 | d2 | d3 | d4 | updated_dict_1 | updated_dict_2 | updated_dict_3 | updated_dict_4

    result = decode(shuffle(rm_noise(a), tab), dic)

    # Записываем в файл
    with open(output_file, 'a', encoding='utf-8') as f:
        f.write(f"Permutation: {permutation}\n")
        f.write(f"Decoded Text: {result}\n\n")


output_file = "results_permutation.txt"

# Очищаем файл перед началом работы
with open(output_file, 'w', encoding='utf-8') as f:
    f.write("Starting decoding...\n\n")


# --- Чтение Permutation из valid_results.txt ---
def read_permutations_from_file(input_file):
    permutations = []
    with open(input_file, 'r', encoding='utf-8') as f:
        for line in f:
            if line.startswith("Permutation:"):
                permutation = list(map(int, line.strip().split("[")[1].split("]")[0].split(", ")))
                permutations.append(permutation)
    return permutations


# --- Генерация словарей на основе valid_results.txt ---
valid_permutations = read_permutations_from_file("results.txt")

# Применяем найденные Permutation
for perm in valid_permutations:
    ex(perm, perm)

print(f"Результаты сохранены в {output_file}")

