a = 'AJNOLJKODNNIKHBKMHPAIEFKJBNGCMEPFEKNEMADIHFJPAHLMCJAOEFIBHAGEFFCAADCHAFNBMMGOBFEDHLIAPDMFCKDCIBHAKMOCJMNFDEEACCGHNDBGHAOEAEAINGBNAIACAHKDGADIDIFMKDNDEADJBFJPDEJOFGOBEADEMOAHNJEKLNCGIFKBHMGIAMEAHHOEAENNOOJOCEBKEAALINHIPAOFBLAKMCIMICFBCKHGHDHKILAIIHDCJAHHGADMAGJLCNAKPAAADEBAANIHJEFBFKBGLKOBHBPEMAOBFJAIDJIOCHABIDFOHNPGDGFCBNAFCAACENAJAJFOHHOCIMOMBNCIIIINIAICAHCBJKFHKPDFDOIMNMDFLOCPDAEDKNHFPKACFHIAKNGKEPGHCOOHEFIIOGAOADCOINMKIMOEPGDMGAAFCOMCCAOEHINOIIIEIHDPJKFPBHNKNOAFCOEGKAOBNINOONCDIFNAFMGANBEBBOACMBEFNAMBAFJHBDJFFABNCDAMMKDIFEFFEKAIEHIANMMAHIEDJAAJBMAJDKBNHKAMAHNCOADAPNOMEANEEADOKFJPDEFKDNAEIODJDAEHLEBNKGGBOKMECFICOFNKNBJGKAMIJEAENECMNLPMCAFONDAMFHPNMJDIADKGMDPIHPINMAICAHMICKFCJGAJGCAHACAGCADJHBBHMECBFMANACEAHGDEKKAFBDCNBNPHLMCNOPMAAFABNBGAJFMFKEILMADDGOJPNEJBLBJAPADFMEAHHPEFHNPCGKKGCDIIBKODLKFDHFKAHHMIHPFODBAOODENHAJJEMHDMKFJPMFODHEAGAHDEAGKHKFLGFINPPDCJBIKIAAANOAAHNOOIBHKICNKBCHALEHKCEAGIADILNJHHDMOJBGDEADKBNAHAHFHENIIFFAEDKGAMLEAEBGJJAMMAFAEPNNKKFAHIMNFCACAFODMPNPPCNDHBDADAMCDGJEGJAOEDMAIEGMOMACPIMKDCMCIHOAMJKACCHOECAFIPOLOGOOGIHFPMOHGADCHDONBFAFIBFAGEGCINHFJEKAMDHIAOKHHACODHAAJIOAJFJPOFBIPIFCPJKGHDACHEAAFHBHGAADFPNJOJFJGIOKPJAIIELCCIGCPHMAOKKEAGFEOCMACNAMENFAELBKFLGAGGLHPENDFFGKDEGILHACKDOAHGGKPGOCFCEMJKMBEKCOKGMACIHNFBAHAHEPAFCPBAMMEJDECHDFOBFADIHNLDNHOCHEEPGOEBDFGOOPGBKEAAGIAAOPDNOICFAHDHJEJHCCDNMHIAMHOHMJHIONBFAIAHGKGMDMFPCAJCBFABFLEHFIMBKAHCKKANJMOEPAOIDFFFNPAOBJHGONEHAMNKFACDCPMOCNAEOKDIONINOBFAMNOGNCILBAHLIICODABHFFDGAGNBLDHJFKJFKMPGKIECEMENCJGBONLCAIAGDHFMDAHMHEBHAFJGPCACOFPJOODPHINLMFMPAGLEFOKPFMOEDLHDOCBFKAOCMIAHDINKMGFOMMBAFCEBBJMHNEPCAKFAIAINHCKOAIKICFCPKHGNHANAKIDGIAPPKEJFJOAODDPAJAPECAACFPCKJENHHCGNMFCKGMADBPCAENLDDBACGAKOAAHICHGIAKFNBPNEPEAOAOOOMANBNPOOOJFICKEJACIJKBPCFEFCAOCBMJNDJKFGFAANDOHBNPIDKEAEMIAAIAGBKEJKNNMDHEPEMKOFMCKCHIMJEMCCAOMIFANFGDADJLLANACEHGAEIIBCLGDMAOLPNAEIHPOPPAKIDFIKNPGAFPAOMMGADANEFHJCGEJGJGDLAAKONAHIEBOCFHDIKMLFCCEKOCACHPMAFDDGDNPBLIBNJAHNNFDPNOGFOBNINAEAFMJOAAEFIGDCIFDPOEDOHIBMEBFNKACGKEMPACJCLBOICAHOKKJOAKIBIBAFMEDAFOEEMGNAPJOOMHCICBNNHHEAMNMPHEHCFHPBMGFHGFHEBFBFKFCMHIGJHOAKIGBAFNGDFNABKMHHMIKFEHEFKBHCMJOIMENIADNNMJPMFNOODAJOCMLBAHEBHAOKJCNINMMBMOCBGEKOEAFINCECAOKJOODKLAMPKCHFNKHBKCHCEECFAMKLIAEFIACIKFBKOACEPIANFNKPMHNIAKNODAIPOBAEAEAJNNFBMAODCKAHEGKAEMIABJEINOFOAALMHOCHAFIIJNFFCOCANMLFNACKGFEOLPHBMNPADCANJMAENAFANAOKFAAOKBAPBIEAEFGBKJGEPMKFCGMKKKOAFICDAHHMGAHHBFCPAEMIAHCEKGNHMKFKFEIOCOHEIJAHAONBEAIAAEMCBJECMKIPAEIDPAFBCJBMAMPJAJEADHKKFACIDMAFAJEBHEMPJCFEOMEFMICBNDKGLAIIHIGBAFEDCCMLJFGECAGPHHAKPICCNBNHADHIEAHBDFNEJCFOMOCDMCOCPBHPIDKHEKNKLBIGLCNCNJAOMKBMACIKDAHLJEPFAKDPIAIGPDFIIEEMAKONIJIFOEFBOAMMKEPLAKJBIFHIHICFADKAOAPNFMKDECBIHKIBMHIDECAMEJPJMDMAAEPNJMAPEGKANFMCBGMALICDLDFCACOCCADDGHNCLFPACMAAHHECBDDDKBDDADDMEAPIJNNMLADAHDPONFPIEAHDDIEHADOAOAHLBEOHGAMIHCBENFHFFKFJIECNDFBLMPGMICAHDGDAHMDHFFCMDIDCPMDJBBDHBMMLGDCHJANFBEGOAMJHFDANCAGAOGLDAIPOCHOGFEPIDOPAMPEBBPCIBILHKNDMKKOOCHABOGOJNONOFAIBOIKIOIBKAOKHOAIBFJAGLPDAKFHADIMBAPHOOIOHOHOCKNHAJMAHFCFJNOJDMAIFPEAALAMAHKOAAFIAJKFPCFAAEMLAHBCBJDAGCAMAMOLMACIAOCDOAGPHOIFIFIHOHLMEFCFEHAJAMHAINPDBKIKPNPFAOACCONMJEJBEKFMHAINMFGDIICCDKADAMIAMOLMAAAFEEDGNNOPJICEBKICJMAOIOEJBEDFPBOAGKAPMNIAMHFMGBHOEKKIICIIDJEFCJIFGMAJBKCADPIDCJFMPNNCAHAAKEEAPECKAFKLDMNIHAKKHNGIICMMHFHCIKKNILIHOADBEKADMDDOAHJFICKCMACIKCMPBDEDCAOLKMJNMNMFOFAINDOHONPINBDAJBMHADAJOFHJAFGKKPHJIDHEMHPFHIBOEKNINAFGFFAGGANAMKAFAHKHCAPICMOEFFPJBDOLFJPIPMPKPKAGINEPFAOJDLHAJCNCANDICOADPFDJHHGPLAANCNAHJEDOHCHAIKMDOCCENFDAGPPNAFDMMDNPBFAOGAEOIECOMMOHNLDCBFACHHDHGAHPINDCHOIBCAKGFOJIJMPODNHHIDKFDCHIEJANLAIFAHCCPKFHADPHOJNMHAFJHFAGPKMFGBEPNDCPDMHHAAODIOHEHLMGBCDEBBEMCDJNCOOHKAIIPCMHDAHBFKFJOCIGMKDOOPKNICAMBKHAIGHMJGAMCAFIBNJGAEDAJMIHACNKBOKOEKNOOLIFIDOHEKHNIPPAMIIMJKAENOIJEGKKAHFNIAKOBHAIAEFMOKHAECAOFHHAOBHKJFCPIFOHGMGNMMEMCEFCEEEAOHOBHOOMNHAPCHDNCAFHEMADIOOFPHFIAOHGLHIOEMJLIOMKBAIEJACHGHMCFKACPBIACDBNGCGPOMMHCFCEDODAIADNAKKIHDIICCAFDOIMAJBFPKPMMJIAHLAAAHNGAAFABFJALOIPJIHJDKEFAHFAKEGIHAODNNAOBKIMJJANEJNFLALGPAHDLECFPOCCEKIHPIAANINPJADAHFAPNDLCNHAAHHMHEAHEOJCDGNJFHOOKDAIINAOOEMPGOANGIDAAGBGFICAEGMKNBNCCOPHHDABPFAOOGEAIHICHAECDFKACJMIACOCNHDGFOMMNGFCEMNEDEFDBHNKNMLAIDBMNCCHMOOMJPCIEIHPNOOJBOMNKKACAECOHMJKDHAOGDCAINPBDBFHGDMMBACEEGAECFLFKHKKIDHIIAGGFBOKGCANNJCAAOECHKJIBHAOJCKAECKBFNFHAMHMLNCFEPIDFFNAIGMCOEACKDBENAAIAANCHHKOHFDFHPIACPOCHCAFKGMFNPNDNOAHAICAPDONCEFJCHFKNOAGIGFMAKEPOJFKFFDNIBLOCOHECCAKNFIAIPIDFKOAIMFCCPNAHJEEMKGCMEDAIAMHAHDCMLAAJECJPHAHPPHNMIBIKEFEIBOGONPEKHKNBIADHCFJPFFHDPCFEHNANFHAAGMDECDAPBNAABFAAFCBFDEIMNFHCFOGFLODDHIIJEKAPFKKAPOGKJIPLKAODNJAOMKLDOPCNHMMAMMCEOHJMHMCFEDFGBMPMJIKJKDJMPOABHAOJBPPFCCIBGAAGHOJAKHCMHEHJCMMKECEEFMJFPDIPGMAOJKCJEEDFIIABMKFPLAKNBKNMDEIAHEFNBOBGEOGANKHFAKAEIHIAFHKFGOAFNDHKONPDKFPOIKEDODALEMHJENFMLGEBCKAKFOIAGEDOIDICONFKAKOGEEIKGBAGIAEEKAJJAKCMPJHLCKAKFHIAECCOKMAFIHFKANFGFBGHCKACFMDMFACPKLOHKCPDHAKHEJAIKPPONONJIHKMCOHINAMHMHNDHAMCMFACHLAMLMNOCAKBPOAIKMINAFDBADKAGDPIBEOODMEMIAEEFMJOJCEAMLHJAEMMGDJEGEMAMLIAJFMNNKACEFKECFFKBNNCBHAALDAFLNADGKEKFACJFJNKMFACIHKFJAHIPEAFKCIDNDDFFKEHKNMBLIMOMBAOBBMACCEKFOADIMDDDACJOKPFGDHHGNNGICAOCHDFMAGEGAOIBFAIIHPDMENAPMEADBEBFHKHHIEFHAFMIMAMNCECOJGDHMKGJFEINPCMJDAOEAONDAJIIHMDIEGHPKAHMFIAFFCAOBOMAKFEENINCJICLJHPHMNNPDEAJPAACMOBJNOKANAIHAIEOBEPJHPJOMFCEOMALIJCAKAJKAIAKLEADLADJNOPMAAIECFKCFPJCODOHDIDFGNADIJPAENNPAJAPHLKJCICIFNBNKGOEBFAFHMIADCJHFHHCLPAKBAGJOHLFAIFLHHMCDHBCAKJKDAICFBNHJOAAKDPOOCPIKENNGAKAFMLHAGEEJIADENNAMNIABEOBOCOHBHNNMHHGCEHNMMEPMGGBKMEKFICAGHKDNADKADPJNAPMLOCIOADKMFEAALMCPBAJOGHAEKJFFBIAAAAIDALJFHKPAAFKODFKBCBGONEFKIABBHAFDPPJFMDHDNEEGLMMKAEEDKNKAHIKGLOIGNKIEAGFFOJNBANKOAEADCJKAHKHMCNKMOKAFMIBEGCCNICEJAHECKPHNKKPFECHAKKHKAIFKIAJCCAMEKNANFGJKANFAAFELIHAAHKFKAHDAFCEEFAHMNHFHEAOHGOLPENIAEBFMJOCEANHDACACJNPAHPNADKBCDPICFMBDHAOKBEPHAOBADFGNAHMLIMKEINCAHMLKJHFADKPMICIDNDMKDOPFECDDAMHDAHMNDALJEKICCDIMMGNMCECGMAOAAHANCBGNGHAGNAAJHMAOAEFCILLGBDFDGBHKICFFIHONDOJEHMICAJKHHAAABNEBICADAHEOHJAFNAKNCKAEDIFMBPCJCNCBADACHJMAHFFLGFBMCIGMMJFKECACCFKEGCGKAKFFIABGDNGMCNONAFACAAHNHKCLJBIAFCPEAGFDMKOKHKCMFGFDEGANBJPJPPLANJIDAAEHHOPDHBIKMCACCEGNEEOBPJJFDKGDNPJEIKBMCAIFAAOKGAIBFKNNAIIFAOMNGABIOEMJJOBNDBLAAHHIPDOMKMHKAOBKIAPIIMMMAKEAKCFNAKKHFAGIEEJADPMMAECPFCPGAJHHMDKAHEBMANHAOIADKEEEPIIINHCHIMHMAOCOCALHNAIEGHJNFCEFAMCGOANLBPAEOPGEJIEGDAOKGAAKKFPFICCFDFILIANDKJHKPKCBHAFFAFAEEGLNBOHIEACEHCJKEMAHIBLBDEHAOJBNMAPNACAHFDAGAPHCADCNHAPKEHHPBAFAOOPEAICOHAEHPOJNAIHBAADGNOBECHOBFHIKNNOHPAGBILAOCDFOIHGHNDHPICPDDGMKDHAFDFIEAAMKNGCAKAEEJFEEKIGFAGFKMAGCACKEADHKFDCAKNBLJADLOHJMKBLEEICKPNJCACAANLPAJAEJPDAIAPENAEAFAACJLACDGJAOOMMFOIFEBAACHJJKBKMHIDFFCCIJOLKOMCBNICNOCFFAIBGMAMPKCAKECKHHIKIHCNKKFHCFMABPAMAHHCDAFFECJKBNPCCOMNNDOCGNFALFEKAENNIMJAACPONOCBIDMDBMPEONBAIJKHAFAKOKMAGOBMANIFCMDKNKCJCIAKGNBBIAOHAEAIHOCHCOGAFNMELFACCCEMIHPPCNNDBDAAMEFMECALEAFKJAJNCKINGDGDACICKFHEIGAKPONDIADHLFJPPCEJAEGJLAIOJNAELMOOPOHAIKMNACCEBNIAJBPCAFDEGDNPHEIHAEABHMCBPNCHDAMDBNCIPNOGCMAICNOHNABGHAMEKEACOGAMDGNHCAKMCOAIEHANIMDKADKIDDPIFHNOGKEOIAENHMJOIGKOCNHDIAMKFDAEFHBAMNHBAKAKMHIAHINANIINAIFHKKEGFEKKNPHLCOHABCIHCJEEHOJDJMOEEAEIFGJKDHCDIFADHKGAJBHNDKIFOFAJDKGAAECMDLAJCANEKFAABFCNLNEKADOLDMPNAFGIJDNEHAFMCFAGEHJDEGIIHAFJHKAGMKCHFODJHAKOADAIOANMIHFMEDKPOHPICNBFIENHAAKFCFACNOBKDOADIMNJEACALJPACDIFAIKICKEKDKCNKBGDACOEIFHOFOBHABOJFAFOBOAGCPGKNFBAINMDLEOCOKPHNDIJFADPCKADOGAAHHIEJEDFPOBPHCDNOBBMHAOHBEAIINONDKIDAFCPJOGHLDLANPIMAOACHOIJGPJOAGANNAANDNAJLGAACDPPANMOMDAEPFDFNNABNDHHFNPDKACKJCENIDABCMDJFNCMEEEOCKAIBOIAFDBNDBIAANFFAKOGBAEDAEAOPBNKFADGNKMMCHIJCAFMBOJGFANAMPIDAMNLJKEOIAMDHBICPDMKNKDCMNMAHBOPJMNLOEEAJOBKGFEEIAOOFMAIAMNCFIANDCFGGADGMLMHOBCHFMALICEAFEMEODACBDCIFNPHAGHBHCDAKOAHDCFABCDNHKAEGDHMAADPAHCHBOIIFFAJFKGANMMDNCCIPNMDAKAENFLOOOAKIBKAPANIIFNALOJCJMFLIAEAFCEANLMAADAGFFHJNGFMKCJBEFOMBAGILDFNKGECAMCDCMCHBJGMECAMEKDBAAKHJJBNBAIGAHFIFKHAFLPMNOJBCKMADAICCGIBKJIOMAFEHOAGCCFEPOMAJDBOFBJMGJMMIDKKCFANMKMANJLIEMHMEMFPOCEGJNNAIEEEAIEBCMEOKMOHHFIHFNDPFOOPJKOPBBNOCNOKLOAICDFKHGIAIAODBOAICOKNHAAHADKJHNDCDJPDDLHKPOAECDIAIBCCDFGEHNONJFAIEKHNDNAOADOEEFHIHOFACNJAANAPNAAAHBGFJMADNDHELNPDBKNADIEKADAGAMHJJOGFDHIAGMOOHKCECJNECEOFJMKIINEILBAHKOAGFAAGDNAAKPIABAOOJKABBNIAEBFKHDCAIAMONKJEHHLKMJADCMDFCACHEIDABGGKAMMFMFEEHHAKFLAGIMHMHACMOFGDPKHDENNPMCAOAILJDFJJPOMLCAIELOHKIFCCICAKPMHAOFDANFIOAHNOOKFOGIDCKOGLHKOAFFIELLPDFHEEHAKPAIAIMLIHINHPFKOJBCIIECOHKOEFFAKKFIAIJIJFPDENMAKOFIJIPMIMBLBDBMNFBMBGMAP'
b = 'KEOIAKDKNDKHKILOMPPBLBMNDKMBAGEE'
e = "K##I#KDK##KHK###M##B#BMN##MBA###"
c = 'KIHICKDKFHKHKCBAMAJBNBMNBGMBANBA'
d = 'MAKBNBMCGKMBDBKKMBPBBBMMENMBBEKE'
#
# # a = 8160
# # b = 32
# # c = 32
# # d = 32
#
# # букв - 16
# # знаков # - 16
# # строка - K##I#KDK##KHK###M##B#BMN##MBA###
#
# # block = 255
#
# print(f"a - {len(a)}\nb = {len(b)}\nc = {len(c)}\nd = {len(d)}")
#
# print(len(a) // len(b))
#
# str_new = ""
# for i in range(len(b)):
#     if b[i] == c[i]:
#         str_new += b[i]
#     else:
#         str_new += '#'
#
# print(str_new)
#
# k = 0
# letter = 0
#
# for i in range(len(e)):
#     if e[i] == "#":
#         k += 1
#     else:
#         letter += 1
#
# print(f"letters - {letter}\n# - {k}")
#
# str_16_first = ""
# str_16_second = ""
# for i in range(len(e)):
#     if i <= 15:
#         str_16_first += e[i]
#     else:
#         str_16_second += e[i]
#
#
# print(f"First half - {str_16_first}\nSecond half - {str_16_second}")
#
# # K##I#KDK##KHK###
# # M##B#BMN##MBA###
#
# str_wthout_noise_1 = ""
# str_wthout_noise_2 = ""
# for i in range(len(str_16_first)):
#     if str_16_first[i] != "#":
#         str_wthout_noise_1 += str_16_first[i]
#     if str_16_second[i] != "#":
#         str_wthout_noise_2 += str_16_second[i]
#
# print(f"First string - {str_wthout_noise_1}\nSecond string - {str_wthout_noise_2}")

numbers_noise = []
for i in range(len(e)):
    if e[i] == "#":
        numbers_noise.append(i)
print(numbers_noise)


print(f"{d[:16]}\n{d[16:32]}")

def rm_noises(d):

    new_d = ""
    for i in range(len(d)):
        if i not in numbers_noise:
            new_d += d[i]

    return new_d

print(f"d: {rm_noises(d)}\n"
      f"b: {rm_noises(b)}\n"
      f"c: {rm_noises(c)}")

'''
Строка d:
MBBMCMBD 1___
12345678
MBBMMMBB ____
Если DC:
1 -> 8
2 -> 5

Если CD:
1 -> 5
2 -> 8

Для строк b и c:

KIKDKKHK 
12345678
MBBMNMBA

пример:

NAFNJOGA= танк
HFKIIEIK= овой

HFKIIEIK овой
12345678

1 -> 7 IK
2 -> 3

 
'''




from textwrap import wrap
def ss(string):
    return [string[i:i+4] for i in range(0, len(string), 4)]

print(f"SS function - {ss(e)}")

def com(x,y):
    r=''
    for i in range(len(x)):
        if x[i] == y[i]:
            r+=x[i]
        else:
            r+='#'
    return r

print(com(b, c))

print(8160 // 16)

'''
KEOI AKDK NDKH KILO 
KIHI CKDK FHKH KCBA 

MPPB LBMN DKMB AGEE

KIHI CKDK FHKH KCBA 

MPPB LBMN DKMB AGEE
MAJB NBMN BGMB ANBA


Итог:
K__I _KDK __KH K___
M__B _BMN __MB A___

KI KDK KH K
12 345 67 8
MB BMN MB A

Для строки 1:

MAKB NBMC GKMB DBKK 
MBPB BBMM ENMB BEKE

Итог:
MB BMC MB D
12 345 67 8
MB BMM MB B
'''

'''
KIKDKKHKMBBMNMBA
KIKDKKHK - бом
MBBMNMBA - ба_

K##I#KDK##KHK###
M##B#BMN##MBA###



K##I #KDK ##KH K### 
M##B #BMN ##MB A###

2 3 5 9 10 14 15 16 18 19 21 25 26 30 31 32

MAKBNBMCGKMBDBKK
MBPBBBMMENMBBEKE

KBBKMKK

PBBNMKE

Моя строка e:
'K##I', '#KDK', '##KH', 'K###'
'M##B', '#BMN', '##MB', 'A###'

MBBMMMBB
12345678
KIKDKKHK - бомб
MBBMNMBA - а___



'''

d = 'MAKBNBMCGKMBDBKKMBPBBBMMENMBBEKE'

def rm_noise(s):
    # places = [1,2,3,6,8,9,10,13]
    # places = [0, 1, 2, 5, 7, 8, 9, 12]
    places = [1, 2, 4, 8, 9, 13, 14, 15]
    a = wrap(s, 16)  # делим строку на блоки по 32 символа
    r = ''
    for w in a:
        for i in range(len(w)):  # проходим по всем символам блока
            if i not in places:  # добавляем только не шум
                r += w[i]
    return r

f = "EIBBCHMCHDDMABMBIGOBMAMJKGBMOBMB"
s = "MAKBNBMCGKMBDBKKMBPBBBMMENMBBEKE"

print(f"Function - {rm_noise(f)}")

'''
EIBBCHMCHDDMABMB
IGOBMAMJKGBMOBMB
BCMDMBMBBMMBMBMB
BCMDMBMBBMMBMBMB

ECHCMAMBIMAJMOMB


MBBMCMBD
MBBMMMBB

3 4 6 10 11 13 14 15 | + 1
1 2 3 6 8 9 10 13 17 18 19 22 24 25 26 29
'''

print(f"My string - {rm_noise(d)}")

'''
MBBMCMBD
MBBMMMBB

'''


'''
Задание 7E8-11

K I KDK KHK бомб

M B BMN MBA а___

na или an - буква "a"


MAKBNBMC GKMBDBKK
MBPBBBMM ENMBBEKE

'''