a = "AJNOLJKODNNIKHBKMHPAIEFKJBNGCMEPFEKNEMADIHFJPAHLMCJAOEFIBHAGEFFCAADCHAFNBMMGOBFEDHLIAPDMFCKDCIBHAKMOCJMNFDEEACCGHNDBGHAOEAEAINGBNAIACAHKDGADIDIFMKDNDEADJBFJPDEJOFGOBEADEMOAHNJEKLNCGIFKBHMGIAMEAHHOEAENNOOJOCEBKEAALINHIPAOFBLAKMCIMICFBCKHGHDHKILAIIHDCJAHHGADMAGJLCNAKPAAADEBAANIHJEFBFKBGLKOBHBPEMAOBFJAIDJIOCHABIDFOHNPGDGFCBNAFCAACENAJAJFOHHOCIMOMBNCIIIINIAICAHCBJKFHKPDFDOIMNMDFLOCPDAEDKNHFPKACFHIAKNGKEPGHCOOHEFIIOGAOADCOINMKIMOEPGDMGAAFCOMCCAOEHINOIIIEIHDPJKFPBHNKNOAFCOEGKAOBNINOONCDIFNAFMGANBEBBOACMBEFNAMBAFJHBDJFFABNCDAMMKDIFEFFEKAIEHIANMMAHIEDJAAJBMAJDKBNHKAMAHNCOADAPNOMEANEEADOKFJPDEFKDNAEIODJDAEHLEBNKGGBOKMECFICOFNKNBJGKAMIJEAENECMNLPMCAFONDAMFHPNMJDIADKGMDPIHPINMAICAHMICKFCJGAJGCAHACAGCADJHBBHMECBFMANACEAHGDEKKAFBDCNBNPHLMCNOPMAAFABNBGAJFMFKEILMADDGOJPNEJBLBJAPADFMEAHHPEFHNPCGKKGCDIIBKODLKFDHFKAHHMIHPFODBAOODENHAJJEMHDMKFJPMFODHEAGAHDEAGKHKFLGFINPPDCJBIKIAAANOAAHNOOIBHKICNKBCHALEHKCEAGIADILNJHHDMOJBGDEADKBNAHAHFHENIIFFAEDKGAMLEAEBGJJAMMAFAEPNNKKFAHIMNFCACAFODMPNPPCNDHBDADAMCDGJEGJAOEDMAIEGMOMACPIMKDCMCIHOAMJKACCHOECAFIPOLOGOOGIHFPMOHGADCHDONBFAFIBFAGEGCINHFJEKAMDHIAOKHHACODHAAJIOAJFJPOFBIPIFCPJKGHDACHEAAFHBHGAADFPNJOJFJGIOKPJAIIELCCIGCPHMAOKKEAGFEOCMACNAMENFAELBKFLGAGGLHPENDFFGKDEGILHACKDOAHGGKPGOCFCEMJKMBEKCOKGMACIHNFBAHAHEPAFCPBAMMEJDECHDFOBFADIHNLDNHOCHEEPGOEBDFGOOPGBKEAAGIAAOPDNOICFAHDHJEJHCCDNMHIAMHOHMJHIONBFAIAHGKGMDMFPCAJCBFABFLEHFIMBKAHCKKANJMOEPAOIDFFFNPAOBJHGONEHAMNKFACDCPMOCNAEOKDIONINOBFAMNOGNCILBAHLIICODABHFFDGAGNBLDHJFKJFKMPGKIECEMENCJGBONLCAIAGDHFMDAHMHEBHAFJGPCACOFPJOODPHINLMFMPAGLEFOKPFMOEDLHDOCBFKAOCMIAHDINKMGFOMMBAFCEBBJMHNEPCAKFAIAINHCKOAIKICFCPKHGNHANAKIDGIAPPKEJFJOAODDPAJAPECAACFPCKJENHHCGNMFCKGMADBPCAENLDDBACGAKOAAHICHGIAKFNBPNEPEAOAOOOMANBNPOOOJFICKEJACIJKBPCFEFCAOCBMJNDJKFGFAANDOHBNPIDKEAEMIAAIAGBKEJKNNMDHEPEMKOFMCKCHIMJEMCCAOMIFANFGDADJLLANACEHGAEIIBCLGDMAOLPNAEIHPOPPAKIDFIKNPGAFPAOMMGADANEFHJCGEJGJGDLAAKONAHIEBOCFHDIKMLFCCEKOCACHPMAFDDGDNPBLIBNJAHNNFDPNOGFOBNINAEAFMJOAAEFIGDCIFDPOEDOHIBMEBFNKACGKEMPACJCLBOICAHOKKJOAKIBIBAFMEDAFOEEMGNAPJOOMHCICBNNHHEAMNMPHEHCFHPBMGFHGFHEBFBFKFCMHIGJHOAKIGBAFNGDFNABKMHHMIKFEHEFKBHCMJOIMENIADNNMJPMFNOODAJOCMLBAHEBHAOKJCNINMMBMOCBGEKOEAFINCECAOKJOODKLAMPKCHFNKHBKCHCEECFAMKLIAEFIACIKFBKOACEPIANFNKPMHNIAKNODAIPOBAEAEAJNNFBMAODCKAHEGKAEMIABJEINOFOAALMHOCHAFIIJNFFCOCANMLFNACKGFEOLPHBMNPADCANJMAENAFANAOKFAAOKBAPBIEAEFGBKJGEPMKFCGMKKKOAFICDAHHMGAHHBFCPAEMIAHCEKGNHMKFKFEIOCOHEIJAHAONBEAIAAEMCBJECMKIPAEIDPAFBCJBMAMPJAJEADHKKFACIDMAFAJEBHEMPJCFEOMEFMICBNDKGLAIIHIGBAFEDCCMLJFGECAGPHHAKPICCNBNHADHIEAHBDFNEJCFOMOCDMCOCPBHPIDKHEKNKLBIGLCNCNJAOMKBMACIKDAHLJEPFAKDPIAIGPDFIIEEMAKONIJIFOEFBOAMMKEPLAKJBIFHIHICFADKAOAPNFMKDECBIHKIBMHIDECAMEJPJMDMAAEPNJMAPEGKANFMCBGMALICDLDFCACOCCADDGHNCLFPACMAAHHECBDDDKBDDADDMEAPIJNNMLADAHDPONFPIEAHDDIEHADOAOAHLBEOHGAMIHCBENFHFFKFJIECNDFBLMPGMICAHDGDAHMDHFFCMDIDCPMDJBBDHBMMLGDCHJANFBEGOAMJHFDANCAGAOGLDAIPOCHOGFEPIDOPAMPEBBPCIBILHKNDMKKOOCHABOGOJNONOFAIBOIKIOIBKAOKHOAIBFJAGLPDAKFHADIMBAPHOOIOHOHOCKNHAJMAHFCFJNOJDMAIFPEAALAMAHKOAAFIAJKFPCFAAEMLAHBCBJDAGCAMAMOLMACIAOCDOAGPHOIFIFIHOHLMEFCFEHAJAMHAINPDBKIKPNPFAOACCONMJEJBEKFMHAINMFGDIICCDKADAMIAMOLMAAAFEEDGNNOPJICEBKICJMAOIOEJBEDFPBOAGKAPMNIAMHFMGBHOEKKIICIIDJEFCJIFGMAJBKCADPIDCJFMPNNCAHAAKEEAPECKAFKLDMNIHAKKHNGIICMMHFHCIKKNILIHOADBEKADMDDOAHJFICKCMACIKCMPBDEDCAOLKMJNMNMFOFAINDOHONPINBDAJBMHADAJOFHJAFGKKPHJIDHEMHPFHIBOEKNINAFGFFAGGANAMKAFAHKHCAPICMOEFFPJBDOLFJPIPMPKPKAGINEPFAOJDLHAJCNCANDICOADPFDJHHGPLAANCNAHJEDOHCHAIKMDOCCENFDAGPPNAFDMMDNPBFAOGAEOIECOMMOHNLDCBFACHHDHGAHPINDCHOIBCAKGFOJIJMPODNHHIDKFDCHIEJANLAIFAHCCPKFHADPHOJNMHAFJHFAGPKMFGBEPNDCPDMHHAAODIOHEHLMGBCDEBBEMCDJNCOOHKAIIPCMHDAHBFKFJOCIGMKDOOPKNICAMBKHAIGHMJGAMCAFIBNJGAEDAJMIHACNKBOKOEKNOOLIFIDOHEKHNIPPAMIIMJKAENOIJEGKKAHFNIAKOBHAIAEFMOKHAECAOFHHAOBHKJFCPIFOHGMGNMMEMCEFCEEEAOHOBHOOMNHAPCHDNCAFHEMADIOOFPHFIAOHGLHIOEMJLIOMKBAIEJACHGHMCFKACPBIACDBNGCGPOMMHCFCEDODAIADNAKKIHDIICCAFDOIMAJBFPKPMMJIAHLAAAHNGAAFABFJALOIPJIHJDKEFAHFAKEGIHAODNNAOBKIMJJANEJNFLALGPAHDLECFPOCCEKIHPIAANINPJADAHFAPNDLCNHAAHHMHEAHEOJCDGNJFHOOKDAIINAOOEMPGOANGIDAAGBGFICAEGMKNBNCCOPHHDABPFAOOGEAIHICHAECDFKACJMIACOCNHDGFOMMNGFCEMNEDEFDBHNKNMLAIDBMNCCHMOOMJPCIEIHPNOOJBOMNKKACAECOHMJKDHAOGDCAINPBDBFHGDMMBACEEGAECFLFKHKKIDHIIAGGFBOKGCANNJCAAOECHKJIBHAOJCKAECKBFNFHAMHMLNCFEPIDFFNAIGMCOEACKDBENAAIAANCHHKOHFDFHPIACPOCHCAFKGMFNPNDNOAHAICAPDONCEFJCHFKNOAGIGFMAKEPOJFKFFDNIBLOCOHECCAKNFIAIPIDFKOAIMFCCPNAHJEEMKGCMEDAIAMHAHDCMLAAJECJPHAHPPHNMIBIKEFEIBOGONPEKHKNBIADHCFJPFFHDPCFEHNANFHAAGMDECDAPBNAABFAAFCBFDEIMNFHCFOGFLODDHIIJEKAPFKKAPOGKJIPLKAODNJAOMKLDOPCNHMMAMMCEOHJMHMCFEDFGBMPMJIKJKDJMPOABHAOJBPPFCCIBGAAGHOJAKHCMHEHJCMMKECEEFMJFPDIPGMAOJKCJEEDFIIABMKFPLAKNBKNMDEIAHEFNBOBGEOGANKHFAKAEIHIAFHKFGOAFNDHKONPDKFPOIKEDODALEMHJENFMLGEBCKAKFOIAGEDOIDICONFKAKOGEEIKGBAGIAEEKAJJAKCMPJHLCKAKFHIAECCOKMAFIHFKANFGFBGHCKACFMDMFACPKLOHKCPDHAKHEJAIKPPONONJIHKMCOHINAMHMHNDHAMCMFACHLAMLMNOCAKBPOAIKMINAFDBADKAGDPIBEOODMEMIAEEFMJOJCEAMLHJAEMMGDJEGEMAMLIAJFMNNKACEFKECFFKBNNCBHAALDAFLNADGKEKFACJFJNKMFACIHKFJAHIPEAFKCIDNDDFFKEHKNMBLIMOMBAOBBMACCEKFOADIMDDDACJOKPFGDHHGNNGICAOCHDFMAGEGAOIBFAIIHPDMENAPMEADBEBFHKHHIEFHAFMIMAMNCECOJGDHMKGJFEINPCMJDAOEAONDAJIIHMDIEGHPKAHMFIAFFCAOBOMAKFEENINCJICLJHPHMNNPDEAJPAACMOBJNOKANAIHAIEOBEPJHPJOMFCEOMALIJCAKAJKAIAKLEADLADJNOPMAAIECFKCFPJCODOHDIDFGNADIJPAENNPAJAPHLKJCICIFNBNKGOEBFAFHMIADCJHFHHCLPAKBAGJOHLFAIFLHHMCDHBCAKJKDAICFBNHJOAAKDPOOCPIKENNGAKAFMLHAGEEJIADENNAMNIABEOBOCOHBHNNMHHGCEHNMMEPMGGBKMEKFICAGHKDNADKADPJNAPMLOCIOADKMFEAALMCPBAJOGHAEKJFFBIAAAAIDALJFHKPAAFKODFKBCBGONEFKIABBHAFDPPJFMDHDNEEGLMMKAEEDKNKAHIKGLOIGNKIEAGFFOJNBANKOAEADCJKAHKHMCNKMOKAFMIBEGCCNICEJAHECKPHNKKPFECHAKKHKAIFKIAJCCAMEKNANFGJKANFAAFELIHAAHKFKAHDAFCEEFAHMNHFHEAOHGOLPENIAEBFMJOCEANHDACACJNPAHPNADKBCDPICFMBDHAOKBEPHAOBADFGNAHMLIMKEINCAHMLKJHFADKPMICIDNDMKDOPFECDDAMHDAHMNDALJEKICCDIMMGNMCECGMAOAAHANCBGNGHAGNAAJHMAOAEFCILLGBDFDGBHKICFFIHONDOJEHMICAJKHHAAABNEBICADAHEOHJAFNAKNCKAEDIFMBPCJCNCBADACHJMAHFFLGFBMCIGMMJFKECACCFKEGCGKAKFFIABGDNGMCNONAFACAAHNHKCLJBIAFCPEAGFDMKOKHKCMFGFDEGANBJPJPPLANJIDAAEHHOPDHBIKMCACCEGNEEOBPJJFDKGDNPJEIKBMCAIFAAOKGAIBFKNNAIIFAOMNGABIOEMJJOBNDBLAAHHIPDOMKMHKAOBKIAPIIMMMAKEAKCFNAKKHFAGIEEJADPMMAECPFCPGAJHHMDKAHEBMANHAOIADKEEEPIIINHCHIMHMAOCOCALHNAIEGHJNFCEFAMCGOANLBPAEOPGEJIEGDAOKGAAKKFPFICCFDFILIANDKJHKPKCBHAFFAFAEEGLNBOHIEACEHCJKEMAHIBLBDEHAOJBNMAPNACAHFDAGAPHCADCNHAPKEHHPBAFAOOPEAICOHAEHPOJNAIHBAADGNOBECHOBFHIKNNOHPAGBILAOCDFOIHGHNDHPICPDDGMKDHAFDFIEAAMKNGCAKAEEJFEEKIGFAGFKMAGCACKEADHKFDCAKNBLJADLOHJMKBLEEICKPNJCACAANLPAJAEJPDAIAPENAEAFAACJLACDGJAOOMMFOIFEBAACHJJKBKMHIDFFCCIJOLKOMCBNICNOCFFAIBGMAMPKCAKECKHHIKIHCNKKFHCFMABPAMAHHCDAFFECJKBNPCCOMNNDOCGNFALFEKAENNIMJAACPONOCBIDMDBMPEONBAIJKHAFAKOKMAGOBMANIFCMDKNKCJCIAKGNBBIAOHAEAIHOCHCOGAFNMELFACCCEMIHPPCNNDBDAAMEFMECALEAFKJAJNCKINGDGDACICKFHEIGAKPONDIADHLFJPPCEJAEGJLAIOJNAELMOOPOHAIKMNACCEBNIAJBPCAFDEGDNPHEIHAEABHMCBPNCHDAMDBNCIPNOGCMAICNOHNABGHAMEKEACOGAMDGNHCAKMCOAIEHANIMDKADKIDDPIFHNOGKEOIAENHMJOIGKOCNHDIAMKFDAEFHBAMNHBAKAKMHIAHINANIINAIFHKKEGFEKKNPHLCOHABCIHCJEEHOJDJMOEEAEIFGJKDHCDIFADHKGAJBHNDKIFOFAJDKGAAECMDLAJCANEKFAABFCNLNEKADOLDMPNAFGIJDNEHAFMCFAGEHJDEGIIHAFJHKAGMKCHFODJHAKOADAIOANMIHFMEDKPOHPICNBFIENHAAKFCFACNOBKDOADIMNJEACALJPACDIFAIKICKEKDKCNKBGDACOEIFHOFOBHABOJFAFOBOAGCPGKNFBAINMDLEOCOKPHNDIJFADPCKADOGAAHHIEJEDFPOBPHCDNOBBMHAOHBEAIINONDKIDAFCPJOGHLDLANPIMAOACHOIJGPJOAGANNAANDNAJLGAACDPPANMOMDAEPFDFNNABNDHHFNPDKACKJCENIDABCMDJFNCMEEEOCKAIBOIAFDBNDBIAANFFAKOGBAEDAEAOPBNKFADGNKMMCHIJCAFMBOJGFANAMPIDAMNLJKEOIAMDHBICPDMKNKDCMNMAHBOPJMNLOEEAJOBKGFEEIAOOFMAIAMNCFIANDCFGGADGMLMHOBCHFMALICEAFEMEODACBDCIFNPHAGHBHCDAKOAHDCFABCDNHKAEGDHMAADPAHCHBOIIFFAJFKGANMMDNCCIPNMDAKAENFLOOOAKIBKAPANIIFNALOJCJMFLIAEAFCEANLMAADAGFFHJNGFMKCJBEFOMBAGILDFNKGECAMCDCMCHBJGMECAMEKDBAAKHJJBNBAIGAHFIFKHAFLPMNOJBCKMADAICCGIBKJIOMAFEHOAGCCFEPOMAJDBOFBJMGJMMIDKKCFANMKMANJLIEMHMEMFPOCEGJNNAIEEEAIEBCMEOKMOHHFIHFNDPFOOPJKOPBBNOCNOKLOAICDFKHGIAIAODBOAICOKNHAAHADKJHNDCDJPDDLHKPOAECDIAIBCCDFGEHNONJFAIEKHNDNAOADOEEFHIHOFACNJAANAPNAAAHBGFJMADNDHELNPDBKNADIEKADAGAMHJJOGFDHIAGMOOHKCECJNECEOFJMKIINEILBAHKOAGFAAGDNAAKPIABAOOJKABBNIAEBFKHDCAIAMONKJEHHLKMJADCMDFCACHEIDABGGKAMMFMFEEHHAKFLAGIMHMHACMOFGDPKHDENNPMCAOAILJDFJJPOMLCAIELOHKIFCCICAKPMHAOFDANFIOAHNOOKFOGIDCKOGLHKOAFFIELLPDFHEEHAKPAIAIMLIHINHPFKOJBCIIECOHKOEFFAKKFIAIJIJFPDENMAKOFIJIPMIMBLBDBMNFBMBGMAP"
b = "KEOIAKDKNDKHKILOMPPBLBMNDKMBAGEE"
e = "K##I#KDK##KHK###M##B#BMN##MBA###"
c = "KIHICKDKFHKHKCBAMAJBNBMNBGMBANBA"
d = "MAKBNBMCGKMBDBKKMBPBBBMMENMBBEKE"

filtered_blocks = []
positions_to_remove = [1, 2, 4, 8, 9, 13, 14, 15, 17, 18, 20, 24, 25, 29, 30, 31]
blocks = []

for i in range(0, len(a), 32):
    block = a[i:i + 32]

    # Заменяем символы на '#' на указанных позициях
    modified_block = ''.join([char if j not in positions_to_remove else '#' for j, char in enumerate(block)])

    # # Проверяем наличие нужных символов в модифицированном блоке
    # if (modified_block.count('N') >= 1 and modified_block.count('A') >= 1 and
    #         modified_block.count('K') >= 2 and modified_block.count('D') >= 1 and
    #         modified_block.count('I') >= 1 and modified_block.count('H') >= 1):
    blocks.append(modified_block)

# Выводим результат
for i, char in enumerate(blocks):
    print(f"i: {i} | blocks: \nбомб: {char[:16]}\na___: {char[16:32]}\n")

# filtered_blocks = []
# positions_to_remove = [1, 2, 4, 8, 9, 13, 14, 15, 17, 18, 20, 24, 25, 29, 30, 31]
# blocks = []
#
# for i in range(0, len(a), 32):
#     block = a[i:i + 32]
#
#     # filtered_block = ''.join([char for j, char in enumerate(block) if j not in positions_to_remove])
#
#
#     if (block.count('N') >= 1 and block.count('A') >= 1 and
#             block.count('K') >= 2 and block.count('D') >= 1 and
#             block.count('I') >= 1 and block.count('H') >= 1):
#         blocks.append(block)
#
#
# for i, char in enumerate(blocks):
#     print(f"i: {i} | blocks: \nбомб: {char[:16]}\na___: {char[16:32]}\n")

# # Проходим по строке с шагом 32
# for i in range(0, len(a), 32):
#     block = a[i:i+32]
#
#     filtered_block = ''.join([char for j, char in enumerate(block) if j not in positions_to_remove])
#
#     if block.count('N') >= 1 and block.count('A') >= 1 and block.count('K') >= 2 and block.count('D') >= 1 and block.count("I") >= 1 and block.count("H") >= 1:
#
#         # filtered_block = ''.join([char for j, char in enumerate(block) if j not in positions_to_remove])
#         filtered_blocks.append(filtered_block)
#
# for i, char in enumerate(filtered_blocks):
#     print(f"i: {i} | blocks: \nбомб: {char[:8]}\na___: {char[8:16]}\n")

# def compare_blocks(b, c):
#     # Сравнение символов двух блоков
#     return ''.join([x if x == y else '#' for x, y in zip(b, c)])
#
# comparison_result = compare_blocks(b, c)
# print(f"Сравнение b и c: \n{comparison_result}")
#
# def remove_noise(block, noise_indices):
#     # Убираем шум по известным индексам шума
#     return ''.join([block[i] for i in range(len(block)) if i not in noise_indices])
#
#
# noise_indices = [1, 2, 4, 8, 9, 13, 14, 15, 17, 18, 20, 24, 25, 29, 30, 31]  # Индексы шума (пример)
# clean_block = remove_noise(comparison_result, noise_indices)
# print(f"Очищенный блок: \n{clean_block}")
